//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarSystem.Mars.ViewController.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContentRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolarSystem.Mars.ViewController.Resources.ContentRessources", typeof(ContentRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations d&apos;authentification.
        /// </summary>
        public static string AuthentificationInformations {
            get {
                return ResourceManager.GetString("AuthentificationInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provenance.
        /// </summary>
        public static string CityFrom {
            get {
                return ResourceManager.GetString("CityFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conférences.
        /// </summary>
        public static string Conferences {
            get {
                return ResourceManager.GetString("Conferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation du mot de passe.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecté en tant que: &lt;strong&gt;{0}&lt;/strong&gt; &lt;strong&gt;{1}&lt;/strong.
        /// </summary>
        public static string ConnectedAs {
            get {
                return ResourceManager.GetString("ConnectedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations de contact.
        /// </summary>
        public static string ContactInformations {
            get {
                return ResourceManager.GetString("ContactInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email EPSI.
        /// </summary>
        public static string EPSIEmail {
            get {
                return ResourceManager.GetString("EPSIEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xyz@epsi.fr.
        /// </summary>
        public static string EPSIEmail_PlaceHorder {
            get {
                return ResourceManager.GetString("EPSIEmail_PlaceHorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations relatives à l&apos;EPSI.
        /// </summary>
        public static string EPSIInformations {
            get {
                return ResourceManager.GetString("EPSIInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.epsilab.net.
        /// </summary>
        public static string EPSILabUrl {
            get {
                return ResourceManager.GetString("EPSILabUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.facebook.com/.
        /// </summary>
        public static string Facebook_PlaceHolder {
            get {
                return ResourceManager.GetString("Facebook_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;oubliez pas le &lt;em&gt;http://www.facebook.com/&lt;/em&gt;.
        /// </summary>
        public static string Facebook_Recommandation {
            get {
                return ResourceManager.GetString("Facebook_Recommandation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page GitHub.
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.github.com/.
        /// </summary>
        public static string GitHub_PlaceHolder {
            get {
                return ResourceManager.GetString("GitHub_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;oubliez pas le &lt;em&gt;http://www.github.com/&lt;/em&gt;.
        /// </summary>
        public static string GitHub_Recommandation {
            get {
                return ResourceManager.GetString("GitHub_Recommandation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page LinkedIn.
        /// </summary>
        public static string LinkedIn {
            get {
                return ResourceManager.GetString("LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://fr.linkedin.com/.
        /// </summary>
        public static string LinkedIn_PlaceHolder {
            get {
                return ResourceManager.GetString("LinkedIn_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;oubliez pas le &lt;em&gt;http://*.linkedin.com/&lt;/em&gt;.
        /// </summary>
        public static string LinkedIn_Recommandation {
            get {
                return ResourceManager.GetString("LinkedIn_Recommandation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes à présent connecté au portail. Vous avez désormais accès aux sections auxquelles vous pouvez gérer les informations..
        /// </summary>
        public static string LogOn_Connected {
            get {
                return ResourceManager.GetString("LogOn_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autres.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email personnel.
        /// </summary>
        public static string PersonalEmail {
            get {
                return ResourceManager.GetString("PersonalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xyz@outlook.com.
        /// </summary>
        public static string PersonalEmail_PlaceHolder {
            get {
                return ResourceManager.GetString("PersonalEmail_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations personnelles.
        /// </summary>
        public static string PersonalInformations {
            get {
                return ResourceManager.GetString("PersonalInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0102030405.
        /// </summary>
        public static string PhoneNumber_PlaceHolder {
            get {
                return ResourceManager.GetString("PhoneNumber_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows.
        /// </summary>
        public static string Shows {
            get {
                return ResourceManager.GetString("Shows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diaporama du site.
        /// </summary>
        public static string Slideshow {
            get {
                return ResourceManager.GetString("Slideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faîtes-vous connaître !.
        /// </summary>
        public static string SocialInformations {
            get {
                return ResourceManager.GetString("SocialInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.twitter.com/.
        /// </summary>
        public static string Twitter_PlaceHolder {
            get {
                return ResourceManager.GetString("Twitter_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;oubliez pas le &lt;em&gt;http://www.twitter.com/&lt;/em&gt;.
        /// </summary>
        public static string Twitter_Recommandation {
            get {
                return ResourceManager.GetString("Twitter_Recommandation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom utilisateur.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider la demande de création de compte.
        /// </summary>
        public static string ValidAccountRequest {
            get {
                return ResourceManager.GetString("ValidAccountRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Viadeo.
        /// </summary>
        public static string Viadeo {
            get {
                return ResourceManager.GetString("Viadeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.viadeo.com/.
        /// </summary>
        public static string Viadeo_PlaceHolder {
            get {
                return ResourceManager.GetString("Viadeo_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;oubliez pas le &lt;em&gt;http://www.viadeo.com/&lt;/em&gt;.
        /// </summary>
        public static string Viadeo_Recommandation {
            get {
                return ResourceManager.GetString("Viadeo_Recommandation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site web.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://.
        /// </summary>
        public static string Website_PlaceHolder {
            get {
                return ResourceManager.GetString("Website_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;oubliez pas le &lt;em&gt;http://&lt;/em&gt;.
        /// </summary>
        public static string Website_Recommandation {
            get {
                return ResourceManager.GetString("Website_Recommandation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue sur le portail d&apos;administration de l&apos;association &lt;strong&gt;EPSILab&lt;/strong&gt;. Pour accéder aux paramètres, veuillez vous connecter avec votre &lt;strong&gt;nom utilisateur&lt;/strong&gt; et votre &lt;strong&gt;mot de passe&lt;/strong&gt;..
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si vous ne possédez pas de compte, vous pouvez en faire la demande en cliquant sur &lt;strong&gt;Demander la création d&apos;un compte&lt;/strong&gt;..
        /// </summary>
        public static string WelcomeText2 {
            get {
                return ResourceManager.GetString("WelcomeText2", resourceCulture);
            }
        }
    }
}
