//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarSystem.Mars.ViewController.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContentRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolarSystem.Mars.ViewController.Resources.ContentRessources", typeof(ContentRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations d&apos;authentification.
        /// </summary>
        public static string AuthentificationInformations {
            get {
                return ResourceManager.GetString("AuthentificationInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auteur.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour à la page précédente.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus.
        /// </summary>
        public static string Campus {
            get {
                return ResourceManager.GetString("Campus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provenance.
        /// </summary>
        public static string CityFrom {
            get {
                return ResourceManager.GetString("CityFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails sur la conférence.
        /// </summary>
        public static string ConferenceDescription {
            get {
                return ResourceManager.GetString("ConferenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations sur l&apos;organisation de la conférence.
        /// </summary>
        public static string ConferenceInformations {
            get {
                return ResourceManager.GetString("ConferenceInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conférences.
        /// </summary>
        public static string Conferences {
            get {
                return ResourceManager.GetString("Conferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation du mot de passe.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecté en tant que &lt;strong&gt;{0}&lt;/strong&gt; &lt;strong&gt;{1}&lt;/strong&gt;.
        /// </summary>
        public static string ConnectedAs {
            get {
                return ResourceManager.GetString("ConnectedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations de contact.
        /// </summary>
        public static string ContactInformations {
            get {
                return ResourceManager.GetString("ContactInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to du {0} au {1}.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date et heure.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Heure fin.
        /// </summary>
        public static string EndDateTime {
            get {
                return ResourceManager.GetString("EndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email EPSI.
        /// </summary>
        public static string EPSIEmail {
            get {
                return ResourceManager.GetString("EPSIEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xyz@epsi.fr.
        /// </summary>
        public static string EPSIEmail_PlaceHorder {
            get {
                return ResourceManager.GetString("EPSIEmail_PlaceHorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations relatives à l&apos;EPSI.
        /// </summary>
        public static string EPSIInformations {
            get {
                return ResourceManager.GetString("EPSIInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.epsilab.net.
        /// </summary>
        public static string EPSILabUrl {
            get {
                return ResourceManager.GetString("EPSILabUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.facebook.com/.
        /// </summary>
        public static string Facebook_PlaceHolder {
            get {
                return ResourceManager.GetString("Facebook_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;oubliez pas le &lt;em&gt;http://www.facebook.com/&lt;/em&gt;.
        /// </summary>
        public static string Facebook_Recommandation {
            get {
                return ResourceManager.GetString("Facebook_Recommandation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrouver mon mot de passe.
        /// </summary>
        public static string FindMyPassword {
            get {
                return ResourceManager.GetString("FindMyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous pouvez utiliser ce formulaire pour effectuer une demande de restauration du mot de passe. Indiquez-nous votre &lt;strong&gt;nom utilisateur&lt;/strong&gt; ainsi que votre &lt;strong&gt;adresse e-mail&lt;/strong&gt;. Un mail vous sera ensuite envoyé pour redéfinir votre mot de passe..
        /// </summary>
        public static string FindMyPasswordText {
            get {
                return ResourceManager.GetString("FindMyPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page GitHub.
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.github.com/.
        /// </summary>
        public static string GitHub_PlaceHolder {
            get {
                return ResourceManager.GetString("GitHub_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;oubliez pas le &lt;em&gt;http://www.github.com/&lt;/em&gt;.
        /// </summary>
        public static string GitHub_Recommandation {
            get {
                return ResourceManager.GetString("GitHub_Recommandation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publié?.
        /// </summary>
        public static string IsPublished {
            get {
                return ResourceManager.GetString("IsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mots-clés.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to séparés avec des mots-clés.
        /// </summary>
        public static string Keywords_Recommandation {
            get {
                return ResourceManager.GetString("Keywords_Recommandation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page LinkedIn.
        /// </summary>
        public static string LinkedIn {
            get {
                return ResourceManager.GetString("LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://fr.linkedin.com/.
        /// </summary>
        public static string LinkedIn_PlaceHolder {
            get {
                return ResourceManager.GetString("LinkedIn_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;oubliez pas le &lt;em&gt;http://*.linkedin.com/&lt;/em&gt;.
        /// </summary>
        public static string LinkedIn_Recommandation {
            get {
                return ResourceManager.GetString("LinkedIn_Recommandation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liens.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télécharger une image depuis votre disque dur.
        /// </summary>
        public static string LocalImage {
            get {
                return ResourceManager.GetString("LocalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes à présent connecté au portail. Vous avez désormais accès aux sections auxquelles vous pouvez gérer les informations..
        /// </summary>
        public static string LogOn_Connected {
            get {
                return ResourceManager.GetString("LogOn_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membres.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenu de l&apos;article.
        /// </summary>
        public static string NewsContent {
            get {
                return ResourceManager.GetString("NewsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations sur l&apos;article.
        /// </summary>
        public static string NewsInformations {
            get {
                return ResourceManager.GetString("NewsInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre de la news.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivant.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordre.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autres.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email personnel.
        /// </summary>
        public static string PersonalEmail {
            get {
                return ResourceManager.GetString("PersonalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xyz@outlook.com.
        /// </summary>
        public static string PersonalEmail_PlaceHolder {
            get {
                return ResourceManager.GetString("PersonalEmail_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations personnelles.
        /// </summary>
        public static string PersonalInformations {
            get {
                return ResourceManager.GetString("PersonalInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0102030405.
        /// </summary>
        public static string PhoneNumber_PlaceHolder {
            get {
                return ResourceManager.GetString("PhoneNumber_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieu.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Précédent.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avancement (%).
        /// </summary>
        public static string Progression {
            get {
                return ResourceManager.GetString("Progression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description du projet.
        /// </summary>
        public static string ProjectDescription {
            get {
                return ResourceManager.GetString("ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations sur le projet.
        /// </summary>
        public static string ProjectInformations {
            get {
                return ResourceManager.GetString("ProjectInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projets.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lier une image présente sur un autre site web.
        /// </summary>
        public static string RemoteImage {
            get {
                return ResourceManager.GetString("RemoteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte d&apos;accroche.
        /// </summary>
        public static string ShortText {
            get {
                return ResourceManager.GetString("ShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails sur le salon.
        /// </summary>
        public static string ShowDescription {
            get {
                return ResourceManager.GetString("ShowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations sur l&apos;organisation du salon.
        /// </summary>
        public static string ShowInformations {
            get {
                return ResourceManager.GetString("ShowInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salons.
        /// </summary>
        public static string Shows {
            get {
                return ResourceManager.GetString("Shows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diaporama du site.
        /// </summary>
        public static string Slideshow {
            get {
                return ResourceManager.GetString("Slideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faîtes-vous connaître !.
        /// </summary>
        public static string SocialInformations {
            get {
                return ResourceManager.GetString("SocialInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Début.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Heure début.
        /// </summary>
        public static string StartDateTime {
            get {
                return ResourceManager.GetString("StartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenu.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.twitter.com/.
        /// </summary>
        public static string Twitter_PlaceHolder {
            get {
                return ResourceManager.GetString("Twitter_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;oubliez pas le &lt;em&gt;http://www.twitter.com/&lt;/em&gt;.
        /// </summary>
        public static string Twitter_Recommandation {
            get {
                return ResourceManager.GetString("Twitter_Recommandation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permalien.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom utilisateur.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider les modifications.
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider la demande de création de compte.
        /// </summary>
        public static string ValidAccountRequest {
            get {
                return ResourceManager.GetString("ValidAccountRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Viadeo.
        /// </summary>
        public static string Viadeo {
            get {
                return ResourceManager.GetString("Viadeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.viadeo.com/.
        /// </summary>
        public static string Viadeo_PlaceHolder {
            get {
                return ResourceManager.GetString("Viadeo_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;oubliez pas le &lt;em&gt;http://www.viadeo.com/&lt;/em&gt;.
        /// </summary>
        public static string Viadeo_Recommandation {
            get {
                return ResourceManager.GetString("Viadeo_Recommandation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site web.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://.
        /// </summary>
        public static string Website_PlaceHolder {
            get {
                return ResourceManager.GetString("Website_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;oubliez pas le &lt;em&gt;http://&lt;/em&gt;.
        /// </summary>
        public static string Website_Recommandation {
            get {
                return ResourceManager.GetString("Website_Recommandation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue sur le portail d&apos;administration de l&apos;association &lt;strong&gt;EPSILab&lt;/strong&gt;. Pour accéder aux paramètres, veuillez vous connecter avec votre &lt;strong&gt;nom utilisateur&lt;/strong&gt; et votre &lt;strong&gt;mot de passe&lt;/strong&gt;..
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si vous ne possédez pas de compte, vous pouvez en faire la demande en cliquant sur &lt;strong&gt;Demander la création d&apos;un compte&lt;/strong&gt;..
        /// </summary>
        public static string WelcomeText2 {
            get {
                return ResourceManager.GetString("WelcomeText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
