//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarSystem.Mars.ViewController.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorRessources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolarSystem.Mars.ViewController.Resources.ErrorRessources", typeof(ErrorRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;auteur est requis..
        /// </summary>
        public static string AuthorRequired {
            get {
                return ResourceManager.GetString("AuthorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectionner votre campus..
        /// </summary>
        public static string CampusRequired {
            get {
                return ResourceManager.GetString("CampusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La ville de provenance est obligatoire..
        /// </summary>
        public static string CityFromRequired {
            get {
                return ResourceManager.GetString("CityFromRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La confirmation du mot de passe est requise..
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;email de contact est requis..
        /// </summary>
        public static string ContactEmailRequired {
            get {
                return ResourceManager.GetString("ContactEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date est requise..
        /// </summary>
        public static string DateRequired {
            get {
                return ResourceManager.GetString("DateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de l&apos;email est incorrect..
        /// </summary>
        public static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date de fin est requise..
        /// </summary>
        public static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;heure de fin est requise..
        /// </summary>
        public static string EndTimeRequired {
            get {
                return ResourceManager.GetString("EndTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de l&apos;adresse EPSI n&apos;est pas correct..
        /// </summary>
        public static string EPSIEmailFormat {
            get {
                return ResourceManager.GetString("EPSIEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;email EPSI est requis..
        /// </summary>
        public static string EPSIEmailRequired {
            get {
                return ResourceManager.GetString("EPSIEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Certains champs ne sont pas valides. Merci de vérifier..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;URL de la page Facebook est incorrecte..
        /// </summary>
        public static string FacebookUrlFormatError {
            get {
                return ResourceManager.GetString("FacebookUrlFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le prénom est obligatoire..
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;URL de la page GitHub est incorrecte..
        /// </summary>
        public static string GitHubUrlFormatError {
            get {
                return ResourceManager.GetString("GitHubUrlFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez entrer une année valide..
        /// </summary>
        public static string GraduationYearLength {
            get {
                return ResourceManager.GetString("GraduationYearLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;année d&apos;obtention du diplôme doit être précisée..
        /// </summary>
        public static string GraduationYearRequired {
            get {
                return ResourceManager.GetString("GraduationYearRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;extension de l&apos;image n&apos;est pas correcte (*.jpg, *.jpeg, *gif, *.png uniquement)..
        /// </summary>
        public static string ImagePathExtensions {
            get {
                return ResourceManager.GetString("ImagePathExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;image doit être valide..
        /// </summary>
        public static string ImagePathFormat {
            get {
                return ResourceManager.GetString("ImagePathFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;image est requise..
        /// </summary>
        public static string ImageRequired {
            get {
                return ResourceManager.GetString("ImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom utilisateur et/ou le mot de passe est incorrect..
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les mots-clés sont obligatoires..
        /// </summary>
        public static string KeywordsRequired {
            get {
                return ResourceManager.GetString("KeywordsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La longueur du libellé doit être de 100 caractères maximum..
        /// </summary>
        public static string LabelMaxLength {
            get {
                return ResourceManager.GetString("LabelMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La longueur du libellé doit être de 2 caractères minimum..
        /// </summary>
        public static string LabelMinLength {
            get {
                return ResourceManager.GetString("LabelMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le libellé est requis..
        /// </summary>
        public static string LabelRequired {
            get {
                return ResourceManager.GetString("LabelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;URL de la page LinkedIn est incorrecte..
        /// </summary>
        public static string LinkedInUrlFormatError {
            get {
                return ResourceManager.GetString("LinkedInUrlFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La longueur du contenu doit être de 10 caractères minimum..
        /// </summary>
        public static string LongTextMinLength {
            get {
                return ResourceManager.GetString("LongTextMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le contenu ne peut pas être vide..
        /// </summary>
        public static string LongTextRequired {
            get {
                return ResourceManager.GetString("LongTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez indiquer vos motivations et vos raisons pour avoir décidé de rejoindre l&apos;association..
        /// </summary>
        public static string MotivationsRequired {
            get {
                return ResourceManager.GetString("MotivationsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La longueur du nom doit être de 100 caractères maximum..
        /// </summary>
        public static string NameMaxLength {
            get {
                return ResourceManager.GetString("NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La longueur du nom doit être de 5 caractères minimum..
        /// </summary>
        public static string NameMinLength {
            get {
                return ResourceManager.GetString("NameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom est requis.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La longueur du nom utilisateur doit être de 6 caractères au minimum..
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe est requis..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de l&apos;adresse personnelle n&apos;est pas correct..
        /// </summary>
        public static string PersonalEmailFormat {
            get {
                return ResourceManager.GetString("PersonalEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le numéro de téléphone saisi doit être valide..
        /// </summary>
        public static string PhoneNumberFormat {
            get {
                return ResourceManager.GetString("PhoneNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le lieu est requis..
        /// </summary>
        public static string PlaceRequired {
            get {
                return ResourceManager.GetString("PlaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La présentation doit être de 30 caractères minimum.
        /// </summary>
        public static string PresentationMinLength {
            get {
                return ResourceManager.GetString("PresentationMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci de faire une petite présentation de vous..
        /// </summary>
        public static string PresentationRequired {
            get {
                return ResourceManager.GetString("PresentationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez indiquer un avancement en %..
        /// </summary>
        public static string ProgressionRequired {
            get {
                return ResourceManager.GetString("ProgressionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectionner votre promo..
        /// </summary>
        public static string PromoRequired {
            get {
                return ResourceManager.GetString("PromoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les mots de passes doivent être identiques..
        /// </summary>
        public static string SamePasswords {
            get {
                return ResourceManager.GetString("SamePasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La longueur de l&apos;accroche doit être de 100 caractères maximum..
        /// </summary>
        public static string ShortTextMaxLength {
            get {
                return ResourceManager.GetString("ShortTextMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La longueur de l&apos;accroche doit être de 5 caractères minimum..
        /// </summary>
        public static string ShortTextMinLength {
            get {
                return ResourceManager.GetString("ShortTextMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le texte court est requis..
        /// </summary>
        public static string ShortTextRequired {
            get {
                return ResourceManager.GetString("ShortTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date de début est requise..
        /// </summary>
        public static string StartDateRequired {
            get {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;heure de début est requise..
        /// </summary>
        public static string StartTimeRequired {
            get {
                return ResourceManager.GetString("StartTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez indiquer si la promotion est encore présente ou non..
        /// </summary>
        public static string StillPresentRequired {
            get {
                return ResourceManager.GetString("StillPresentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom est obligatoire..
        /// </summary>
        public static string SurnameRequired {
            get {
                return ResourceManager.GetString("SurnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;heure est requise..
        /// </summary>
        public static string TimeRequired {
            get {
                return ResourceManager.GetString("TimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La longueur du titre doit être de 100 caractères maximum..
        /// </summary>
        public static string TitleMaxLength {
            get {
                return ResourceManager.GetString("TitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La longueur du titre doit être de 5 caractères minimum..
        /// </summary>
        public static string TitleMinLength {
            get {
                return ResourceManager.GetString("TitleMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le titre est obligatoire..
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;URL de la page Twitter est incorrecte..
        /// </summary>
        public static string TwitterUrlFormatError {
            get {
                return ResourceManager.GetString("TwitterUrlFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;URL est requise..
        /// </summary>
        public static string UrlRequired {
            get {
                return ResourceManager.GetString("UrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom utilisateur ne peut pas dépasser 20 caractères..
        /// </summary>
        public static string UsernameMaxLength {
            get {
                return ResourceManager.GetString("UsernameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La longueur du nom utilisateur doit être de 4 caractères au minimum..
        /// </summary>
        public static string UsernameMinLength {
            get {
                return ResourceManager.GetString("UsernameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom utilisateur est obligatoire..
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Certaines informations saisies dans le formulaire ne sont pas correctes..
        /// </summary>
        public static string ValidationErrorMessage {
            get {
                return ResourceManager.GetString("ValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;URL de la page Viadeo est incorrecte..
        /// </summary>
        public static string ViadeoUrlFormatError {
            get {
                return ResourceManager.GetString("ViadeoUrlFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adresse du site web doit être correcte..
        /// </summary>
        public static string WebsiteUrlFormat {
            get {
                return ResourceManager.GetString("WebsiteUrlFormat", resourceCulture);
            }
        }
    }
}
