//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarSystem.Mars.ViewController.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolarSystem.Mars.ViewController.Resources.ErrorRessources", typeof(ErrorRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;auteur est requis..
        /// </summary>
        public static string AuthorRequired {
            get {
                return ResourceManager.GetString("AuthorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner votre campus..
        /// </summary>
        public static string CampusRequired {
            get {
                return ResourceManager.GetString("CampusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ville de provenance est obligatoire..
        /// </summary>
        public static string CityFromRequired {
            get {
                return ResourceManager.GetString("CityFromRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La confirmation du mot de passe est requise..
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date et l&apos;heure sont requis..
        /// </summary>
        public static string DateTimeRequired {
            get {
                return ResourceManager.GetString("DateTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le format de l&apos;adresse EPSI n&apos;est pas correct..
        /// </summary>
        public static string EPSIEmailFormat {
            get {
                return ResourceManager.GetString("EPSIEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;email EPSI est requis..
        /// </summary>
        public static string EPSIEmailRequired {
            get {
                return ResourceManager.GetString("EPSIEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;URL de la page Facebook est incorrecte..
        /// </summary>
        public static string FacebookUrlFormatError {
            get {
                return ResourceManager.GetString("FacebookUrlFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le prénom est obligatoire..
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;URL de la page GitHub est incorrecte..
        /// </summary>
        public static string GitHubUrlFormatError {
            get {
                return ResourceManager.GetString("GitHubUrlFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;extension de l&apos;image n&apos;est pas correcte (*.jpg, *.jpeg, *gif, *.png uniquement)..
        /// </summary>
        public static string ImagePathExtensions {
            get {
                return ResourceManager.GetString("ImagePathExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;image doit être valide..
        /// </summary>
        public static string ImagePathFormat {
            get {
                return ResourceManager.GetString("ImagePathFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;image est requise..
        /// </summary>
        public static string ImageRequired {
            get {
                return ResourceManager.GetString("ImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;URL de la page LinkedIn est incorrecte..
        /// </summary>
        public static string LinkedInUrlFormatError {
            get {
                return ResourceManager.GetString("LinkedInUrlFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le texte long est requis..
        /// </summary>
        public static string LongTextRequired {
            get {
                return ResourceManager.GetString("LongTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez indiquer vos motivations et vos raisons pour avoir décidé de rejoindre l&apos;association..
        /// </summary>
        public static string MotivationsRequired {
            get {
                return ResourceManager.GetString("MotivationsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longueur du nom utilisateur doit être de 6 caractères au minimum..
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe est requis..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le format de l&apos;adresse personnelle n&apos;est pas correct..
        /// </summary>
        public static string PersonalEmailFormat {
            get {
                return ResourceManager.GetString("PersonalEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le numéro de téléphone saisi doit être valide..
        /// </summary>
        public static string PhoneNumberFormat {
            get {
                return ResourceManager.GetString("PhoneNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci de faire une petite présentation de vous..
        /// </summary>
        public static string PresentationRequired {
            get {
                return ResourceManager.GetString("PresentationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner votre promo..
        /// </summary>
        public static string PromoRequired {
            get {
                return ResourceManager.GetString("PromoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les mots de passes doivent être identiques..
        /// </summary>
        public static string SamePasswords {
            get {
                return ResourceManager.GetString("SamePasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longueur du texte court doit être de 100 caractères maximum..
        /// </summary>
        public static string ShortTextMaxLength {
            get {
                return ResourceManager.GetString("ShortTextMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longueur du texte court doit être de 5 caractères minimum..
        /// </summary>
        public static string ShortTextMinLength {
            get {
                return ResourceManager.GetString("ShortTextMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le texte court est requis..
        /// </summary>
        public static string ShortTextRequired {
            get {
                return ResourceManager.GetString("ShortTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom est obligatoire..
        /// </summary>
        public static string SurnameRequired {
            get {
                return ResourceManager.GetString("SurnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longueur du titre doit être de 100 caractères maximum..
        /// </summary>
        public static string TitleMaxLength {
            get {
                return ResourceManager.GetString("TitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longueur du titre doit être de 5 caractères minimum..
        /// </summary>
        public static string TitleMinLength {
            get {
                return ResourceManager.GetString("TitleMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le titre est obligatoire..
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;URL de la page Twitter est incorrecte..
        /// </summary>
        public static string TwitterUrlFormatError {
            get {
                return ResourceManager.GetString("TwitterUrlFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;URL est requise..
        /// </summary>
        public static string UrlRequired {
            get {
                return ResourceManager.GetString("UrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom utilisateur ne peut pas dépasser 20 caractères..
        /// </summary>
        public static string UsernameMaxLength {
            get {
                return ResourceManager.GetString("UsernameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longueur du nom utilisateur doit être de 4 caractères au minimum..
        /// </summary>
        public static string UsernameMinLength {
            get {
                return ResourceManager.GetString("UsernameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom utilisateur est obligatoire..
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certaines informations saisies dans le formulaire ne sont pas correctes..
        /// </summary>
        public static string ValidationErrorMessage {
            get {
                return ResourceManager.GetString("ValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;URL de la page Viadeo est incorrecte..
        /// </summary>
        public static string ViadeoUrlFormatError {
            get {
                return ResourceManager.GetString("ViadeoUrlFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse du site web doit être correcte..
        /// </summary>
        public static string WebsiteUrlFormat {
            get {
                return ResourceManager.GetString("WebsiteUrlFormat", resourceCulture);
            }
        }
    }
}
