//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarSystem.Mars.ViewController.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolarSystem.Mars.ViewController.Resources.MessagesResources", typeof(MessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le campus a bien été crée..
        /// </summary>
        public static string CampusCreated {
            get {
                return ResourceManager.GetString("CampusCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le campus a bien été mis à jour..
        /// </summary>
        public static string CampusUpdated {
            get {
                return ResourceManager.GetString("CampusUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La conférence a bien été créée..
        /// </summary>
        public static string ConferenceCreated {
            get {
                return ResourceManager.GetString("ConferenceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La conférence a bien été supprimée..
        /// </summary>
        public static string ConferenceDeleted {
            get {
                return ResourceManager.GetString("ConferenceDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La conférence a bien été modifiée..
        /// </summary>
        public static string ConferenceUpdated {
            get {
                return ResourceManager.GetString("ConferenceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer cette conférence ?.
        /// </summary>
        public static string DeleteConference {
            get {
                return ResourceManager.GetString("DeleteConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer ce lien ?.
        /// </summary>
        public static string DeleteLink {
            get {
                return ResourceManager.GetString("DeleteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer cette news ?.
        /// </summary>
        public static string DeleteNews {
            get {
                return ResourceManager.GetString("DeleteNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer ce projet ?.
        /// </summary>
        public static string DeleteProject {
            get {
                return ResourceManager.GetString("DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer ce salon ?.
        /// </summary>
        public static string DeleteShow {
            get {
                return ResourceManager.GetString("DeleteShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer le message ?.
        /// </summary>
        public static string DeleteSlide {
            get {
                return ResourceManager.GetString("DeleteSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le lien a bien été crée..
        /// </summary>
        public static string LinkCreated {
            get {
                return ResourceManager.GetString("LinkCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le lien a bien été supprimé..
        /// </summary>
        public static string LinkDeleted {
            get {
                return ResourceManager.GetString("LinkDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le lien a bien été mis à jour..
        /// </summary>
        public static string LinkUpdated {
            get {
                return ResourceManager.GetString("LinkUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre demande de restauration du mot de passe a bien été enregistrée. Vous allez normalement recevoir un mail pour le redéfinir..
        /// </summary>
        public static string LostPasswordRequestSent {
            get {
                return ResourceManager.GetString("LostPasswordRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La news a bien été créée..
        /// </summary>
        public static string NewsCreated {
            get {
                return ResourceManager.GetString("NewsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La news a bien été supprimée..
        /// </summary>
        public static string NewsDeleted {
            get {
                return ResourceManager.GetString("NewsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La news a bien été modifiée..
        /// </summary>
        public static string NewsUpdated {
            get {
                return ResourceManager.GetString("NewsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le projet a bien été crée..
        /// </summary>
        public static string ProjectCreated {
            get {
                return ResourceManager.GetString("ProjectCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le projet a bien été supprimé..
        /// </summary>
        public static string ProjectDeleted {
            get {
                return ResourceManager.GetString("ProjectDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le projet a bien été mis à jour..
        /// </summary>
        public static string ProjectUpdated {
            get {
                return ResourceManager.GetString("ProjectUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La promotion a bien été créée..
        /// </summary>
        public static string PromotionCreated {
            get {
                return ResourceManager.GetString("PromotionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La promotion a bien été mise à jour..
        /// </summary>
        public static string PromotionUpdated {
            get {
                return ResourceManager.GetString("PromotionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le salon a bien été crée..
        /// </summary>
        public static string ShowCreated {
            get {
                return ResourceManager.GetString("ShowCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le salon a bien été supprimé..
        /// </summary>
        public static string ShowDeleted {
            get {
                return ResourceManager.GetString("ShowDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le salon a bien été mis à jour..
        /// </summary>
        public static string ShowUpdated {
            get {
                return ResourceManager.GetString("ShowUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le message a bien été créée..
        /// </summary>
        public static string SlideCreated {
            get {
                return ResourceManager.GetString("SlideCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le message a bien été supprimée..
        /// </summary>
        public static string SlideDeleted {
            get {
                return ResourceManager.GetString("SlideDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le message a bien été modifiée..
        /// </summary>
        public static string SlideUpdated {
            get {
                return ResourceManager.GetString("SlideUpdated", resourceCulture);
            }
        }
    }
}
