//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarSystem.Mars.ViewController.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolarSystem.Mars.ViewController.Resources.MessagesResources", typeof(MessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le campus a bien été crée..
        /// </summary>
        public static string CampusCreated {
            get {
                return ResourceManager.GetString("CampusCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le campus a bien été mis à jour..
        /// </summary>
        public static string CampusUpdated {
            get {
                return ResourceManager.GetString("CampusUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La conférence a bien été créée..
        /// </summary>
        public static string ConferenceCreated {
            get {
                return ResourceManager.GetString("ConferenceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La conférence a bien été supprimée..
        /// </summary>
        public static string ConferenceDeleted {
            get {
                return ResourceManager.GetString("ConferenceDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La conférence a bien été modifiée..
        /// </summary>
        public static string ConferenceUpdated {
            get {
                return ResourceManager.GetString("ConferenceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer cette conférence ?.
        /// </summary>
        public static string DeleteConference {
            get {
                return ResourceManager.GetString("DeleteConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer ce lien ?.
        /// </summary>
        public static string DeleteLink {
            get {
                return ResourceManager.GetString("DeleteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer cet utilisateur ?.
        /// </summary>
        public static string DeleteMember {
            get {
                return ResourceManager.GetString("DeleteMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer cette news ?.
        /// </summary>
        public static string DeleteNews {
            get {
                return ResourceManager.GetString("DeleteNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer ce projet ?.
        /// </summary>
        public static string DeleteProject {
            get {
                return ResourceManager.GetString("DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer ce salon ?.
        /// </summary>
        public static string DeleteShow {
            get {
                return ResourceManager.GetString("DeleteShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer le message ?.
        /// </summary>
        public static string DeleteSlide {
            get {
                return ResourceManager.GetString("DeleteSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue..
        /// </summary>
        public static string ErrorIssue {
            get {
                return ResourceManager.GetString("ErrorIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le lien a bien été crée..
        /// </summary>
        public static string LinkCreated {
            get {
                return ResourceManager.GetString("LinkCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le lien a bien été supprimé..
        /// </summary>
        public static string LinkDeleted {
            get {
                return ResourceManager.GetString("LinkDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le lien a bien été mis à jour..
        /// </summary>
        public static string LinkUpdated {
            get {
                return ResourceManager.GetString("LinkUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre demande de restauration du mot de passe a bien été enregistrée. Vous allez normalement recevoir un mail pour le redéfinir..
        /// </summary>
        public static string LostPasswordRequestSent {
            get {
                return ResourceManager.GetString("LostPasswordRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le membre a bien été supprimé..
        /// </summary>
        public static string MemberDeleted {
            get {
                return ResourceManager.GetString("MemberDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le membre a bien été modifié..
        /// </summary>
        public static string MemberUpdated {
            get {
                return ResourceManager.GetString("MemberUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La news a bien été créée..
        /// </summary>
        public static string NewsCreated {
            get {
                return ResourceManager.GetString("NewsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La news a bien été supprimée..
        /// </summary>
        public static string NewsDeleted {
            get {
                return ResourceManager.GetString("NewsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette news n&apos;existe pas..
        /// </summary>
        public static string NewsInexistant {
            get {
                return ResourceManager.GetString("NewsInexistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La news a bien été modifiée..
        /// </summary>
        public static string NewsUpdated {
            get {
                return ResourceManager.GetString("NewsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette page n&apos;existe pas..
        /// </summary>
        public static string PageInexistant {
            get {
                return ResourceManager.GetString("PageInexistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le projet a bien été crée..
        /// </summary>
        public static string ProjectCreated {
            get {
                return ResourceManager.GetString("ProjectCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le projet a bien été supprimé..
        /// </summary>
        public static string ProjectDeleted {
            get {
                return ResourceManager.GetString("ProjectDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce projet n&apos;existe pas..
        /// </summary>
        public static string ProjectInexistant {
            get {
                return ResourceManager.GetString("ProjectInexistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le projet a bien été mis à jour..
        /// </summary>
        public static string ProjectUpdated {
            get {
                return ResourceManager.GetString("ProjectUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La promotion a bien été créée..
        /// </summary>
        public static string PromotionCreated {
            get {
                return ResourceManager.GetString("PromotionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La promotion a bien été mise à jour..
        /// </summary>
        public static string PromotionUpdated {
            get {
                return ResourceManager.GetString("PromotionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le salon a bien été crée..
        /// </summary>
        public static string ShowCreated {
            get {
                return ResourceManager.GetString("ShowCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le salon a bien été supprimé..
        /// </summary>
        public static string ShowDeleted {
            get {
                return ResourceManager.GetString("ShowDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce salon n&apos;existe pas..
        /// </summary>
        public static string ShowInexistant {
            get {
                return ResourceManager.GetString("ShowInexistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le salon a bien été mis à jour..
        /// </summary>
        public static string ShowUpdated {
            get {
                return ResourceManager.GetString("ShowUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le message a bien été créée..
        /// </summary>
        public static string SlideCreated {
            get {
                return ResourceManager.GetString("SlideCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le message a bien été supprimée..
        /// </summary>
        public static string SlideDeleted {
            get {
                return ResourceManager.GetString("SlideDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le message a bien été modifiée..
        /// </summary>
        public static string SlideUpdated {
            get {
                return ResourceManager.GetString("SlideUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;êtes pas autorisé à accéder à cette page..
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;avez pas les droits suffisants pour effectuer cette action..
        /// </summary>
        public static string UnauthorizedRight {
            get {
                return ResourceManager.GetString("UnauthorizedRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir valider cet utilisateur ?.
        /// </summary>
        public static string ValidMember {
            get {
                return ResourceManager.GetString("ValidMember", resourceCulture);
            }
        }
    }
}
