//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarSystem.Mars.ViewController.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PagesTitlesRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PagesTitlesRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolarSystem.Mars.ViewController.Resources.PagesTitlesRessources", typeof(PagesTitlesRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les campus.
        /// </summary>
        public static string Campuses {
            get {
                return ResourceManager.GetString("Campuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organiser une nouvelle conférence.
        /// </summary>
        public static string Conference_Create {
            get {
                return ResourceManager.GetString("Conference_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer une conférence.
        /// </summary>
        public static string Conference_Edit {
            get {
                return ResourceManager.GetString("Conference_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des conférences.
        /// </summary>
        public static string Conferences {
            get {
                return ResourceManager.GetString("Conferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier mon profil.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un nouveau lien.
        /// </summary>
        public static string Link_Create {
            get {
                return ResourceManager.GetString("Link_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier un lien.
        /// </summary>
        public static string Link_Edit {
            get {
                return ResourceManager.GetString("Link_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des liens.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portail d&apos;administration.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déconnexion.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié ?.
        /// </summary>
        public static string LostPassword {
            get {
                return ResourceManager.GetString("LostPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrer un nouveau membre.
        /// </summary>
        public static string Member_Create {
            get {
                return ResourceManager.GetString("Member_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider les nouvelles inscriptions.
        /// </summary>
        public static string Member_Valid {
            get {
                return ResourceManager.GetString("Member_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des membres.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des articles.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rédiger un nouvel article.
        /// </summary>
        public static string News_Create {
            get {
                return ResourceManager.GetString("News_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer un article.
        /// </summary>
        public static string News_Edit {
            get {
                return ResourceManager.GetString("News_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lancer un nouveau projet.
        /// </summary>
        public static string Project_Create {
            get {
                return ResourceManager.GetString("Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier un projet.
        /// </summary>
        public static string Project_Edit {
            get {
                return ResourceManager.GetString("Project_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des projets.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les promotions.
        /// </summary>
        public static string Promotions {
            get {
                return ResourceManager.GetString("Promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demander la création d&apos;un compte.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annoncer un nouveau salon.
        /// </summary>
        public static string Show_Create {
            get {
                return ResourceManager.GetString("Show_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier un salon.
        /// </summary>
        public static string Show_Edit {
            get {
                return ResourceManager.GetString("Show_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des salons.
        /// </summary>
        public static string Shows {
            get {
                return ResourceManager.GetString("Shows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des messages du diaporama.
        /// </summary>
        public static string Slideshow {
            get {
                return ResourceManager.GetString("Slideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annoncer un nouveau message.
        /// </summary>
        public static string Slideshow_Create {
            get {
                return ResourceManager.GetString("Slideshow_Create", resourceCulture);
            }
        }
    }
}
