//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarSystem.Mars.Model.ManagersService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Promotion", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Promotion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GraduationYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StillPresentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GraduationYear {
            get {
                return this.GraduationYearField;
            }
            set {
                if ((this.GraduationYearField.Equals(value) != true)) {
                    this.GraduationYearField = value;
                    this.RaisePropertyChanged("GraduationYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StillPresent {
            get {
                return this.StillPresentField;
            }
            set {
                if ((this.StillPresentField.Equals(value) != true)) {
                    this.StillPresentField = value;
                    this.RaisePropertyChanged("StillPresent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Conference", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Conference : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SolarSystem.Mars.Model.ManagersService.Campus CampusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime End_DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Start_DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SolarSystem.Mars.Model.ManagersService.Campus Campus {
            get {
                return this.CampusField;
            }
            set {
                if ((object.ReferenceEquals(this.CampusField, value) != true)) {
                    this.CampusField = value;
                    this.RaisePropertyChanged("Campus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End_DateTime {
            get {
                return this.End_DateTimeField;
            }
            set {
                if ((this.End_DateTimeField.Equals(value) != true)) {
                    this.End_DateTimeField = value;
                    this.RaisePropertyChanged("End_DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPublished {
            get {
                return this.IsPublishedField;
            }
            set {
                if ((this.IsPublishedField.Equals(value) != true)) {
                    this.IsPublishedField = value;
                    this.RaisePropertyChanged("IsPublished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start_DateTime {
            get {
                return this.Start_DateTimeField;
            }
            set {
                if ((this.Start_DateTimeField.Equals(value) != true)) {
                    this.Start_DateTimeField = value;
                    this.RaisePropertyChanged("Start_DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Campus", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Campus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactEmail {
            get {
                return this.ContactEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactEmailField, value) != true)) {
                    this.ContactEmailField = value;
                    this.RaisePropertyChanged("ContactEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Link", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Link : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label {
            get {
                return this.LabelField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelField, value) != true)) {
                    this.LabelField = value;
                    this.RaisePropertyChanged("Label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Order {
            get {
                return this.OrderField;
            }
            set {
                if ((this.OrderField.Equals(value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Member", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Member : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SolarSystem.Mars.Model.ManagersService.Campus CampusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EPSIEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacebookUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GitHubUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkedInUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonalEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PresentationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SolarSystem.Mars.Model.ManagersService.Promotion PromotionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SolarSystem.Mars.Model.ManagersService.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TwitterUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ViadeoUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SolarSystem.Mars.Model.ManagersService.Campus Campus {
            get {
                return this.CampusField;
            }
            set {
                if ((object.ReferenceEquals(this.CampusField, value) != true)) {
                    this.CampusField = value;
                    this.RaisePropertyChanged("Campus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityFrom {
            get {
                return this.CityFromField;
            }
            set {
                if ((object.ReferenceEquals(this.CityFromField, value) != true)) {
                    this.CityFromField = value;
                    this.RaisePropertyChanged("CityFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EPSIEmail {
            get {
                return this.EPSIEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EPSIEmailField, value) != true)) {
                    this.EPSIEmailField = value;
                    this.RaisePropertyChanged("EPSIEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookUrl {
            get {
                return this.FacebookUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookUrlField, value) != true)) {
                    this.FacebookUrlField = value;
                    this.RaisePropertyChanged("FacebookUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GitHubUrl {
            get {
                return this.GitHubUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.GitHubUrlField, value) != true)) {
                    this.GitHubUrlField = value;
                    this.RaisePropertyChanged("GitHubUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkedInUrl {
            get {
                return this.LinkedInUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkedInUrlField, value) != true)) {
                    this.LinkedInUrlField = value;
                    this.RaisePropertyChanged("LinkedInUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonalEmail {
            get {
                return this.PersonalEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalEmailField, value) != true)) {
                    this.PersonalEmailField = value;
                    this.RaisePropertyChanged("PersonalEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Presentation {
            get {
                return this.PresentationField;
            }
            set {
                if ((object.ReferenceEquals(this.PresentationField, value) != true)) {
                    this.PresentationField = value;
                    this.RaisePropertyChanged("Presentation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SolarSystem.Mars.Model.ManagersService.Promotion Promotion {
            get {
                return this.PromotionField;
            }
            set {
                if ((object.ReferenceEquals(this.PromotionField, value) != true)) {
                    this.PromotionField = value;
                    this.RaisePropertyChanged("Promotion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SolarSystem.Mars.Model.ManagersService.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TwitterUrl {
            get {
                return this.TwitterUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.TwitterUrlField, value) != true)) {
                    this.TwitterUrlField = value;
                    this.RaisePropertyChanged("TwitterUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ViadeoUrl {
            get {
                return this.ViadeoUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ViadeoUrlField, value) != true)) {
                    this.ViadeoUrlField = value;
                    this.RaisePropertyChanged("ViadeoUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website {
            get {
                return this.WebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteField, value) != true)) {
                    this.WebsiteField = value;
                    this.RaisePropertyChanged("Website");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    public enum Role : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MemberActive = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bureau = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="News", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class News : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SolarSystem.Mars.Model.ManagersService.Member MemberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPublished {
            get {
                return this.IsPublishedField;
            }
            set {
                if ((this.IsPublishedField.Equals(value) != true)) {
                    this.IsPublishedField = value;
                    this.RaisePropertyChanged("IsPublished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keywords {
            get {
                return this.KeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordsField, value) != true)) {
                    this.KeywordsField = value;
                    this.RaisePropertyChanged("Keywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SolarSystem.Mars.Model.ManagersService.Member Member {
            get {
                return this.MemberField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberField, value) != true)) {
                    this.MemberField = value;
                    this.RaisePropertyChanged("Member");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortText {
            get {
                return this.ShortTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortTextField, value) != true)) {
                    this.ShortTextField = value;
                    this.RaisePropertyChanged("ShortText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Project : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SolarSystem.Mars.Model.ManagersService.Campus CampusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProgressionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SolarSystem.Mars.Model.ManagersService.Campus Campus {
            get {
                return this.CampusField;
            }
            set {
                if ((object.ReferenceEquals(this.CampusField, value) != true)) {
                    this.CampusField = value;
                    this.RaisePropertyChanged("Campus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Progression {
            get {
                return this.ProgressionField;
            }
            set {
                if ((this.ProgressionField.Equals(value) != true)) {
                    this.ProgressionField = value;
                    this.RaisePropertyChanged("Progression");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Slide", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Slide : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PresentationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPublished {
            get {
                return this.IsPublishedField;
            }
            set {
                if ((this.IsPublishedField.Equals(value) != true)) {
                    this.IsPublishedField = value;
                    this.RaisePropertyChanged("IsPublished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Presentation {
            get {
                return this.PresentationField;
            }
            set {
                if ((object.ReferenceEquals(this.PresentationField, value) != true)) {
                    this.PresentationField = value;
                    this.RaisePropertyChanged("Presentation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Show", Namespace="http://schemas.datacontract.org/2004/07/EPSILab.SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Show : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime End_DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Start_DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End_DateTime {
            get {
                return this.End_DateTimeField;
            }
            set {
                if ((this.End_DateTimeField.Equals(value) != true)) {
                    this.End_DateTimeField = value;
                    this.RaisePropertyChanged("End_DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPublished {
            get {
                return this.IsPublishedField;
            }
            set {
                if ((this.IsPublishedField.Equals(value) != true)) {
                    this.IsPublishedField = value;
                    this.RaisePropertyChanged("IsPublished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start_DateTime {
            get {
                return this.Start_DateTimeField;
            }
            set {
                if ((this.Start_DateTimeField.Equals(value) != true)) {
                    this.Start_DateTimeField = value;
                    this.RaisePropertyChanged("Start_DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagersService.IPromotionManager")]
    public interface IPromotionManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionManager/GetPromotion", ReplyAction="http://tempuri.org/IPromotionManager/GetPromotionResponse")]
        SolarSystem.Mars.Model.ManagersService.Promotion GetPromotion(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionManager/GetPromotions", ReplyAction="http://tempuri.org/IPromotionManager/GetPromotionsResponse")]
        SolarSystem.Mars.Model.ManagersService.Promotion[] GetPromotions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionManager/GetPromotionsAvailables", ReplyAction="http://tempuri.org/IPromotionManager/GetPromotionsAvailablesResponse")]
        SolarSystem.Mars.Model.ManagersService.Promotion[] GetPromotionsAvailables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionManager/AddPromotion", ReplyAction="http://tempuri.org/IPromotionManager/AddPromotionResponse")]
        int AddPromotion(SolarSystem.Mars.Model.ManagersService.Promotion element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionManager/EditPromotion", ReplyAction="http://tempuri.org/IPromotionManager/EditPromotionResponse")]
        void EditPromotion(SolarSystem.Mars.Model.ManagersService.Promotion element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionManager/DeletePromotion", ReplyAction="http://tempuri.org/IPromotionManager/DeletePromotionResponse")]
        void DeletePromotion(int code, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPromotionManagerChannel : SolarSystem.Mars.Model.ManagersService.IPromotionManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PromotionManagerClient : System.ServiceModel.ClientBase<SolarSystem.Mars.Model.ManagersService.IPromotionManager>, SolarSystem.Mars.Model.ManagersService.IPromotionManager {
        
        public PromotionManagerClient() {
        }
        
        public PromotionManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PromotionManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PromotionManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PromotionManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolarSystem.Mars.Model.ManagersService.Promotion GetPromotion(int code) {
            return base.Channel.GetPromotion(code);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Promotion[] GetPromotions() {
            return base.Channel.GetPromotions();
        }
        
        public SolarSystem.Mars.Model.ManagersService.Promotion[] GetPromotionsAvailables() {
            return base.Channel.GetPromotionsAvailables();
        }
        
        public int AddPromotion(SolarSystem.Mars.Model.ManagersService.Promotion element, string username, string password) {
            return base.Channel.AddPromotion(element, username, password);
        }
        
        public void EditPromotion(SolarSystem.Mars.Model.ManagersService.Promotion element, string username, string password) {
            base.Channel.EditPromotion(element, username, password);
        }
        
        public void DeletePromotion(int code, string username, string password) {
            base.Channel.DeletePromotion(code, username, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagersService.IConferenceManager")]
    public interface IConferenceManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceManager/GetConference", ReplyAction="http://tempuri.org/IConferenceManager/GetConferenceResponse")]
        SolarSystem.Mars.Model.ManagersService.Conference GetConference(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceManager/GetConferences", ReplyAction="http://tempuri.org/IConferenceManager/GetConferencesResponse")]
        SolarSystem.Mars.Model.ManagersService.Conference[] GetConferences(int indexFirstResult, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceManager/AddConference", ReplyAction="http://tempuri.org/IConferenceManager/AddConferenceResponse")]
        int AddConference(SolarSystem.Mars.Model.ManagersService.Conference element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceManager/EditConference", ReplyAction="http://tempuri.org/IConferenceManager/EditConferenceResponse")]
        void EditConference(SolarSystem.Mars.Model.ManagersService.Conference element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceManager/DeleteConference", ReplyAction="http://tempuri.org/IConferenceManager/DeleteConferenceResponse")]
        void DeleteConference(int code, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConferenceManagerChannel : SolarSystem.Mars.Model.ManagersService.IConferenceManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConferenceManagerClient : System.ServiceModel.ClientBase<SolarSystem.Mars.Model.ManagersService.IConferenceManager>, SolarSystem.Mars.Model.ManagersService.IConferenceManager {
        
        public ConferenceManagerClient() {
        }
        
        public ConferenceManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConferenceManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConferenceManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConferenceManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolarSystem.Mars.Model.ManagersService.Conference GetConference(int code) {
            return base.Channel.GetConference(code);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Conference[] GetConferences(int indexFirstResult, int numberOfResults) {
            return base.Channel.GetConferences(indexFirstResult, numberOfResults);
        }
        
        public int AddConference(SolarSystem.Mars.Model.ManagersService.Conference element, string username, string password) {
            return base.Channel.AddConference(element, username, password);
        }
        
        public void EditConference(SolarSystem.Mars.Model.ManagersService.Conference element, string username, string password) {
            base.Channel.EditConference(element, username, password);
        }
        
        public void DeleteConference(int code, string username, string password) {
            base.Channel.DeleteConference(code, username, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagersService.ILinkManager")]
    public interface ILinkManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILinkManager/GetLink", ReplyAction="http://tempuri.org/ILinkManager/GetLinkResponse")]
        SolarSystem.Mars.Model.ManagersService.Link GetLink(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILinkManager/GetLinks", ReplyAction="http://tempuri.org/ILinkManager/GetLinksResponse")]
        SolarSystem.Mars.Model.ManagersService.Link[] GetLinks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILinkManager/AddLink", ReplyAction="http://tempuri.org/ILinkManager/AddLinkResponse")]
        int AddLink(SolarSystem.Mars.Model.ManagersService.Link element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILinkManager/EditLink", ReplyAction="http://tempuri.org/ILinkManager/EditLinkResponse")]
        void EditLink(SolarSystem.Mars.Model.ManagersService.Link element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILinkManager/DeleteLink", ReplyAction="http://tempuri.org/ILinkManager/DeleteLinkResponse")]
        void DeleteLink(int code, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILinkManagerChannel : SolarSystem.Mars.Model.ManagersService.ILinkManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LinkManagerClient : System.ServiceModel.ClientBase<SolarSystem.Mars.Model.ManagersService.ILinkManager>, SolarSystem.Mars.Model.ManagersService.ILinkManager {
        
        public LinkManagerClient() {
        }
        
        public LinkManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LinkManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LinkManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LinkManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolarSystem.Mars.Model.ManagersService.Link GetLink(int code) {
            return base.Channel.GetLink(code);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Link[] GetLinks() {
            return base.Channel.GetLinks();
        }
        
        public int AddLink(SolarSystem.Mars.Model.ManagersService.Link element, string username, string password) {
            return base.Channel.AddLink(element, username, password);
        }
        
        public void EditLink(SolarSystem.Mars.Model.ManagersService.Link element, string username, string password) {
            base.Channel.EditLink(element, username, password);
        }
        
        public void DeleteLink(int code, string username, string password) {
            base.Channel.DeleteLink(code, username, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagersService.IMemberManager")]
    public interface IMemberManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManager/GetMember", ReplyAction="http://tempuri.org/IMemberManager/GetMemberResponse")]
        SolarSystem.Mars.Model.ManagersService.Member GetMember(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManager/GetMembersActives", ReplyAction="http://tempuri.org/IMemberManager/GetMembersActivesResponse")]
        SolarSystem.Mars.Model.ManagersService.Member[] GetMembersActives();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManager/GetMembersBureau", ReplyAction="http://tempuri.org/IMemberManager/GetMembersBureauResponse")]
        SolarSystem.Mars.Model.ManagersService.Member[] GetMembersBureau(SolarSystem.Mars.Model.ManagersService.Campus campus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManager/GetMembersNotInBureau", ReplyAction="http://tempuri.org/IMemberManager/GetMembersNotInBureauResponse")]
        SolarSystem.Mars.Model.ManagersService.Member[] GetMembersNotInBureau(SolarSystem.Mars.Model.ManagersService.Campus campus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManager/GetMembersAlumnis", ReplyAction="http://tempuri.org/IMemberManager/GetMembersAlumnisResponse")]
        SolarSystem.Mars.Model.ManagersService.Member[] GetMembersAlumnis(SolarSystem.Mars.Model.ManagersService.Campus campus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManager/GetMembersWaitingForValidation", ReplyAction="http://tempuri.org/IMemberManager/GetMembersWaitingForValidationResponse")]
        SolarSystem.Mars.Model.ManagersService.Member[] GetMembersWaitingForValidation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManager/Login", ReplyAction="http://tempuri.org/IMemberManager/LoginResponse")]
        SolarSystem.Mars.Model.ManagersService.Member Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManager/ChangePassword", ReplyAction="http://tempuri.org/IMemberManager/ChangePasswordResponse")]
        void ChangePassword(string username, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManager/ExistsUsername", ReplyAction="http://tempuri.org/IMemberManager/ExistsUsernameResponse")]
        bool ExistsUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManager/ExistsMember", ReplyAction="http://tempuri.org/IMemberManager/ExistsMemberResponse")]
        bool ExistsMember(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManager/Register", ReplyAction="http://tempuri.org/IMemberManager/RegisterResponse")]
        int Register(SolarSystem.Mars.Model.ManagersService.Member membre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManager/RequestLostPassword", ReplyAction="http://tempuri.org/IMemberManager/RequestLostPasswordResponse")]
        void RequestLostPassword(string username, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManager/SetNewPasswordAfterLost", ReplyAction="http://tempuri.org/IMemberManager/SetNewPasswordAfterLostResponse")]
        void SetNewPasswordAfterLost(string username, string newPassword, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManager/AddMember", ReplyAction="http://tempuri.org/IMemberManager/AddMemberResponse")]
        int AddMember(SolarSystem.Mars.Model.ManagersService.Member element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManager/EditMember", ReplyAction="http://tempuri.org/IMemberManager/EditMemberResponse")]
        void EditMember(SolarSystem.Mars.Model.ManagersService.Member element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManager/DeleteMember", ReplyAction="http://tempuri.org/IMemberManager/DeleteMemberResponse")]
        void DeleteMember(int code, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMemberManagerChannel : SolarSystem.Mars.Model.ManagersService.IMemberManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberManagerClient : System.ServiceModel.ClientBase<SolarSystem.Mars.Model.ManagersService.IMemberManager>, SolarSystem.Mars.Model.ManagersService.IMemberManager {
        
        public MemberManagerClient() {
        }
        
        public MemberManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolarSystem.Mars.Model.ManagersService.Member GetMember(int code) {
            return base.Channel.GetMember(code);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Member[] GetMembersActives() {
            return base.Channel.GetMembersActives();
        }
        
        public SolarSystem.Mars.Model.ManagersService.Member[] GetMembersBureau(SolarSystem.Mars.Model.ManagersService.Campus campus) {
            return base.Channel.GetMembersBureau(campus);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Member[] GetMembersNotInBureau(SolarSystem.Mars.Model.ManagersService.Campus campus) {
            return base.Channel.GetMembersNotInBureau(campus);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Member[] GetMembersAlumnis(SolarSystem.Mars.Model.ManagersService.Campus campus) {
            return base.Channel.GetMembersAlumnis(campus);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Member[] GetMembersWaitingForValidation() {
            return base.Channel.GetMembersWaitingForValidation();
        }
        
        public SolarSystem.Mars.Model.ManagersService.Member Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public void ChangePassword(string username, string oldPassword, string newPassword) {
            base.Channel.ChangePassword(username, oldPassword, newPassword);
        }
        
        public bool ExistsUsername(string username) {
            return base.Channel.ExistsUsername(username);
        }
        
        public bool ExistsMember(string username, string password) {
            return base.Channel.ExistsMember(username, password);
        }
        
        public int Register(SolarSystem.Mars.Model.ManagersService.Member membre) {
            return base.Channel.Register(membre);
        }
        
        public void RequestLostPassword(string username, string email) {
            base.Channel.RequestLostPassword(username, email);
        }
        
        public void SetNewPasswordAfterLost(string username, string newPassword, string key) {
            base.Channel.SetNewPasswordAfterLost(username, newPassword, key);
        }
        
        public int AddMember(SolarSystem.Mars.Model.ManagersService.Member element, string username, string password) {
            return base.Channel.AddMember(element, username, password);
        }
        
        public void EditMember(SolarSystem.Mars.Model.ManagersService.Member element, string username, string password) {
            base.Channel.EditMember(element, username, password);
        }
        
        public void DeleteMember(int code, string username, string password) {
            base.Channel.DeleteMember(code, username, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagersService.INewsManager")]
    public interface INewsManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsManager/GetNews", ReplyAction="http://tempuri.org/INewsManager/GetNewsResponse")]
        SolarSystem.Mars.Model.ManagersService.News GetNews(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsManager/GetListNews", ReplyAction="http://tempuri.org/INewsManager/GetListNewsResponse")]
        SolarSystem.Mars.Model.ManagersService.News[] GetListNews();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsManager/GetListNewsLimited", ReplyAction="http://tempuri.org/INewsManager/GetListNewsLimitedResponse")]
        SolarSystem.Mars.Model.ManagersService.News[] GetListNewsLimited(int indexFirstElement, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsManager/AddNews", ReplyAction="http://tempuri.org/INewsManager/AddNewsResponse")]
        int AddNews(SolarSystem.Mars.Model.ManagersService.News element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsManager/EditNews", ReplyAction="http://tempuri.org/INewsManager/EditNewsResponse")]
        void EditNews(SolarSystem.Mars.Model.ManagersService.News element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsManager/DeleteNews", ReplyAction="http://tempuri.org/INewsManager/DeleteNewsResponse")]
        void DeleteNews(int code, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewsManagerChannel : SolarSystem.Mars.Model.ManagersService.INewsManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewsManagerClient : System.ServiceModel.ClientBase<SolarSystem.Mars.Model.ManagersService.INewsManager>, SolarSystem.Mars.Model.ManagersService.INewsManager {
        
        public NewsManagerClient() {
        }
        
        public NewsManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewsManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolarSystem.Mars.Model.ManagersService.News GetNews(int code) {
            return base.Channel.GetNews(code);
        }
        
        public SolarSystem.Mars.Model.ManagersService.News[] GetListNews() {
            return base.Channel.GetListNews();
        }
        
        public SolarSystem.Mars.Model.ManagersService.News[] GetListNewsLimited(int indexFirstElement, int numberOfResults) {
            return base.Channel.GetListNewsLimited(indexFirstElement, numberOfResults);
        }
        
        public int AddNews(SolarSystem.Mars.Model.ManagersService.News element, string username, string password) {
            return base.Channel.AddNews(element, username, password);
        }
        
        public void EditNews(SolarSystem.Mars.Model.ManagersService.News element, string username, string password) {
            base.Channel.EditNews(element, username, password);
        }
        
        public void DeleteNews(int code, string username, string password) {
            base.Channel.DeleteNews(code, username, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagersService.IProjectManager")]
    public interface IProjectManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectManager/GetProject", ReplyAction="http://tempuri.org/IProjectManager/GetProjectResponse")]
        SolarSystem.Mars.Model.ManagersService.Project GetProject(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectManager/GetProjects", ReplyAction="http://tempuri.org/IProjectManager/GetProjectsResponse")]
        SolarSystem.Mars.Model.ManagersService.Project[] GetProjects(int indexFirstElement, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectManager/AddProject", ReplyAction="http://tempuri.org/IProjectManager/AddProjectResponse")]
        int AddProject(SolarSystem.Mars.Model.ManagersService.Project element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectManager/EditProject", ReplyAction="http://tempuri.org/IProjectManager/EditProjectResponse")]
        void EditProject(SolarSystem.Mars.Model.ManagersService.Project element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectManager/DeleteProject", ReplyAction="http://tempuri.org/IProjectManager/DeleteProjectResponse")]
        void DeleteProject(int code, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProjectManagerChannel : SolarSystem.Mars.Model.ManagersService.IProjectManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectManagerClient : System.ServiceModel.ClientBase<SolarSystem.Mars.Model.ManagersService.IProjectManager>, SolarSystem.Mars.Model.ManagersService.IProjectManager {
        
        public ProjectManagerClient() {
        }
        
        public ProjectManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolarSystem.Mars.Model.ManagersService.Project GetProject(int code) {
            return base.Channel.GetProject(code);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Project[] GetProjects(int indexFirstElement, int numberOfResults) {
            return base.Channel.GetProjects(indexFirstElement, numberOfResults);
        }
        
        public int AddProject(SolarSystem.Mars.Model.ManagersService.Project element, string username, string password) {
            return base.Channel.AddProject(element, username, password);
        }
        
        public void EditProject(SolarSystem.Mars.Model.ManagersService.Project element, string username, string password) {
            base.Channel.EditProject(element, username, password);
        }
        
        public void DeleteProject(int code, string username, string password) {
            base.Channel.DeleteProject(code, username, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagersService.ISlideManager")]
    public interface ISlideManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideManager/GetSlide", ReplyAction="http://tempuri.org/ISlideManager/GetSlideResponse")]
        SolarSystem.Mars.Model.ManagersService.Slide GetSlide(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideManager/GetSlides", ReplyAction="http://tempuri.org/ISlideManager/GetSlidesResponse")]
        SolarSystem.Mars.Model.ManagersService.Slide[] GetSlides();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideManager/AddSlide", ReplyAction="http://tempuri.org/ISlideManager/AddSlideResponse")]
        int AddSlide(SolarSystem.Mars.Model.ManagersService.Slide element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideManager/EditSlide", ReplyAction="http://tempuri.org/ISlideManager/EditSlideResponse")]
        void EditSlide(SolarSystem.Mars.Model.ManagersService.Slide element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlideManager/DeleteSlide", ReplyAction="http://tempuri.org/ISlideManager/DeleteSlideResponse")]
        void DeleteSlide(int code, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISlideManagerChannel : SolarSystem.Mars.Model.ManagersService.ISlideManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SlideManagerClient : System.ServiceModel.ClientBase<SolarSystem.Mars.Model.ManagersService.ISlideManager>, SolarSystem.Mars.Model.ManagersService.ISlideManager {
        
        public SlideManagerClient() {
        }
        
        public SlideManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SlideManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SlideManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SlideManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolarSystem.Mars.Model.ManagersService.Slide GetSlide(int code) {
            return base.Channel.GetSlide(code);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Slide[] GetSlides() {
            return base.Channel.GetSlides();
        }
        
        public int AddSlide(SolarSystem.Mars.Model.ManagersService.Slide element, string username, string password) {
            return base.Channel.AddSlide(element, username, password);
        }
        
        public void EditSlide(SolarSystem.Mars.Model.ManagersService.Slide element, string username, string password) {
            base.Channel.EditSlide(element, username, password);
        }
        
        public void DeleteSlide(int code, string username, string password) {
            base.Channel.DeleteSlide(code, username, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagersService.IShowManager")]
    public interface IShowManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShowManager/GetShow", ReplyAction="http://tempuri.org/IShowManager/GetShowResponse")]
        SolarSystem.Mars.Model.ManagersService.Show GetShow(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShowManager/GetShows", ReplyAction="http://tempuri.org/IShowManager/GetShowsResponse")]
        SolarSystem.Mars.Model.ManagersService.Show[] GetShows(int indexFirstElement, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShowManager/AddShow", ReplyAction="http://tempuri.org/IShowManager/AddShowResponse")]
        int AddShow(SolarSystem.Mars.Model.ManagersService.Show element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShowManager/EditShow", ReplyAction="http://tempuri.org/IShowManager/EditShowResponse")]
        void EditShow(SolarSystem.Mars.Model.ManagersService.Show element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShowManager/DeleteShow", ReplyAction="http://tempuri.org/IShowManager/DeleteShowResponse")]
        void DeleteShow(int code, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShowManagerChannel : SolarSystem.Mars.Model.ManagersService.IShowManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShowManagerClient : System.ServiceModel.ClientBase<SolarSystem.Mars.Model.ManagersService.IShowManager>, SolarSystem.Mars.Model.ManagersService.IShowManager {
        
        public ShowManagerClient() {
        }
        
        public ShowManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShowManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShowManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShowManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolarSystem.Mars.Model.ManagersService.Show GetShow(int code) {
            return base.Channel.GetShow(code);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Show[] GetShows(int indexFirstElement, int numberOfResults) {
            return base.Channel.GetShows(indexFirstElement, numberOfResults);
        }
        
        public int AddShow(SolarSystem.Mars.Model.ManagersService.Show element, string username, string password) {
            return base.Channel.AddShow(element, username, password);
        }
        
        public void EditShow(SolarSystem.Mars.Model.ManagersService.Show element, string username, string password) {
            base.Channel.EditShow(element, username, password);
        }
        
        public void DeleteShow(int code, string username, string password) {
            base.Channel.DeleteShow(code, username, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagersService.ICampusManager")]
    public interface ICampusManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampusManager/GetCampus", ReplyAction="http://tempuri.org/ICampusManager/GetCampusResponse")]
        SolarSystem.Mars.Model.ManagersService.Campus GetCampus(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampusManager/GetCampuses", ReplyAction="http://tempuri.org/ICampusManager/GetCampusesResponse")]
        SolarSystem.Mars.Model.ManagersService.Campus[] GetCampuses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampusManager/AddCampus", ReplyAction="http://tempuri.org/ICampusManager/AddCampusResponse")]
        int AddCampus(SolarSystem.Mars.Model.ManagersService.Campus element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampusManager/EditCampus", ReplyAction="http://tempuri.org/ICampusManager/EditCampusResponse")]
        void EditCampus(SolarSystem.Mars.Model.ManagersService.Campus element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampusManager/DeleteCampus", ReplyAction="http://tempuri.org/ICampusManager/DeleteCampusResponse")]
        void DeleteCampus(int code, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICampusManagerChannel : SolarSystem.Mars.Model.ManagersService.ICampusManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CampusManagerClient : System.ServiceModel.ClientBase<SolarSystem.Mars.Model.ManagersService.ICampusManager>, SolarSystem.Mars.Model.ManagersService.ICampusManager {
        
        public CampusManagerClient() {
        }
        
        public CampusManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CampusManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampusManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampusManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolarSystem.Mars.Model.ManagersService.Campus GetCampus(int code) {
            return base.Channel.GetCampus(code);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Campus[] GetCampuses() {
            return base.Channel.GetCampuses();
        }
        
        public int AddCampus(SolarSystem.Mars.Model.ManagersService.Campus element, string username, string password) {
            return base.Channel.AddCampus(element, username, password);
        }
        
        public void EditCampus(SolarSystem.Mars.Model.ManagersService.Campus element, string username, string password) {
            base.Channel.EditCampus(element, username, password);
        }
        
        public void DeleteCampus(int code, string username, string password) {
            base.Channel.DeleteCampus(code, username, password);
        }
    }
}
