//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarSystem.Mars.Model.ManagersService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Classe", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Classe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Annee_Promo_SortanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_ClasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Encore_PresenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibelleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Annee_Promo_Sortante {
            get {
                return this.Annee_Promo_SortanteField;
            }
            set {
                if ((this.Annee_Promo_SortanteField.Equals(value) != true)) {
                    this.Annee_Promo_SortanteField = value;
                    this.RaisePropertyChanged("Annee_Promo_Sortante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_Classe {
            get {
                return this.Code_ClasseField;
            }
            set {
                if ((this.Code_ClasseField.Equals(value) != true)) {
                    this.Code_ClasseField = value;
                    this.RaisePropertyChanged("Code_Classe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Encore_Presente {
            get {
                return this.Encore_PresenteField;
            }
            set {
                if ((this.Encore_PresenteField.Equals(value) != true)) {
                    this.Encore_PresenteField = value;
                    this.RaisePropertyChanged("Encore_Presente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Libelle {
            get {
                return this.LibelleField;
            }
            set {
                if ((object.ReferenceEquals(this.LibelleField, value) != true)) {
                    this.LibelleField = value;
                    this.RaisePropertyChanged("Libelle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Conference", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Conference : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_ConferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_Heure_DebutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_Heure_FinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LieuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublieeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SolarSystem.Mars.Model.ManagersService.Ville VilleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_Conference {
            get {
                return this.Code_ConferenceField;
            }
            set {
                if ((this.Code_ConferenceField.Equals(value) != true)) {
                    this.Code_ConferenceField = value;
                    this.RaisePropertyChanged("Code_Conference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Heure_Debut {
            get {
                return this.Date_Heure_DebutField;
            }
            set {
                if ((this.Date_Heure_DebutField.Equals(value) != true)) {
                    this.Date_Heure_DebutField = value;
                    this.RaisePropertyChanged("Date_Heure_Debut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Heure_Fin {
            get {
                return this.Date_Heure_FinField;
            }
            set {
                if ((this.Date_Heure_FinField.Equals(value) != true)) {
                    this.Date_Heure_FinField = value;
                    this.RaisePropertyChanged("Date_Heure_Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lieu {
            get {
                return this.LieuField;
            }
            set {
                if ((object.ReferenceEquals(this.LieuField, value) != true)) {
                    this.LieuField = value;
                    this.RaisePropertyChanged("Lieu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Publiee {
            get {
                return this.PublieeField;
            }
            set {
                if ((this.PublieeField.Equals(value) != true)) {
                    this.PublieeField = value;
                    this.RaisePropertyChanged("Publiee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SolarSystem.Mars.Model.ManagersService.Ville Ville {
            get {
                return this.VilleField;
            }
            set {
                if ((object.ReferenceEquals(this.VilleField, value) != true)) {
                    this.VilleField = value;
                    this.RaisePropertyChanged("Ville");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ville", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Ville : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_VilleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibelleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_Ville {
            get {
                return this.Code_VilleField;
            }
            set {
                if ((this.Code_VilleField.Equals(value) != true)) {
                    this.Code_VilleField = value;
                    this.RaisePropertyChanged("Code_Ville");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Libelle {
            get {
                return this.LibelleField;
            }
            set {
                if ((object.ReferenceEquals(this.LibelleField, value) != true)) {
                    this.LibelleField = value;
                    this.RaisePropertyChanged("Libelle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lien", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Lien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_LienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_Lien {
            get {
                return this.Code_LienField;
            }
            set {
                if ((this.Code_LienField.Equals(value) != true)) {
                    this.Code_LienField = value;
                    this.RaisePropertyChanged("Code_Lien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ordre {
            get {
                return this.OrdreField;
            }
            set {
                if ((this.OrdreField.Equals(value) != true)) {
                    this.OrdreField = value;
                    this.RaisePropertyChanged("Ordre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Membre", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Membre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SolarSystem.Mars.Model.ManagersService.Classe ClasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_MembreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email_EPSIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email_persoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mot_de_passeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PresentationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PseudoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SolarSystem.Mars.Model.ManagersService.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Site_webField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telephone_mobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URL_FacebookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URL_LinkedInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URL_TwitterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URL_ViadeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SolarSystem.Mars.Model.ManagersService.Ville VilleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ville_origineField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Actif {
            get {
                return this.ActifField;
            }
            set {
                if ((this.ActifField.Equals(value) != true)) {
                    this.ActifField = value;
                    this.RaisePropertyChanged("Actif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SolarSystem.Mars.Model.ManagersService.Classe Classe {
            get {
                return this.ClasseField;
            }
            set {
                if ((object.ReferenceEquals(this.ClasseField, value) != true)) {
                    this.ClasseField = value;
                    this.RaisePropertyChanged("Classe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_Membre {
            get {
                return this.Code_MembreField;
            }
            set {
                if ((this.Code_MembreField.Equals(value) != true)) {
                    this.Code_MembreField = value;
                    this.RaisePropertyChanged("Code_Membre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email_EPSI {
            get {
                return this.Email_EPSIField;
            }
            set {
                if ((object.ReferenceEquals(this.Email_EPSIField, value) != true)) {
                    this.Email_EPSIField = value;
                    this.RaisePropertyChanged("Email_EPSI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email_perso {
            get {
                return this.Email_persoField;
            }
            set {
                if ((object.ReferenceEquals(this.Email_persoField, value) != true)) {
                    this.Email_persoField = value;
                    this.RaisePropertyChanged("Email_perso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mot_de_passe {
            get {
                return this.Mot_de_passeField;
            }
            set {
                if ((object.ReferenceEquals(this.Mot_de_passeField, value) != true)) {
                    this.Mot_de_passeField = value;
                    this.RaisePropertyChanged("Mot_de_passe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motivations {
            get {
                return this.MotivationsField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivationsField, value) != true)) {
                    this.MotivationsField = value;
                    this.RaisePropertyChanged("Motivations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Presentation {
            get {
                return this.PresentationField;
            }
            set {
                if ((object.ReferenceEquals(this.PresentationField, value) != true)) {
                    this.PresentationField = value;
                    this.RaisePropertyChanged("Presentation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pseudo {
            get {
                return this.PseudoField;
            }
            set {
                if ((object.ReferenceEquals(this.PseudoField, value) != true)) {
                    this.PseudoField = value;
                    this.RaisePropertyChanged("Pseudo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SolarSystem.Mars.Model.ManagersService.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Site_web {
            get {
                return this.Site_webField;
            }
            set {
                if ((object.ReferenceEquals(this.Site_webField, value) != true)) {
                    this.Site_webField = value;
                    this.RaisePropertyChanged("Site_web");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Statut {
            get {
                return this.StatutField;
            }
            set {
                if ((object.ReferenceEquals(this.StatutField, value) != true)) {
                    this.StatutField = value;
                    this.RaisePropertyChanged("Statut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone_mobile {
            get {
                return this.Telephone_mobileField;
            }
            set {
                if ((object.ReferenceEquals(this.Telephone_mobileField, value) != true)) {
                    this.Telephone_mobileField = value;
                    this.RaisePropertyChanged("Telephone_mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL_Facebook {
            get {
                return this.URL_FacebookField;
            }
            set {
                if ((object.ReferenceEquals(this.URL_FacebookField, value) != true)) {
                    this.URL_FacebookField = value;
                    this.RaisePropertyChanged("URL_Facebook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL_LinkedIn {
            get {
                return this.URL_LinkedInField;
            }
            set {
                if ((object.ReferenceEquals(this.URL_LinkedInField, value) != true)) {
                    this.URL_LinkedInField = value;
                    this.RaisePropertyChanged("URL_LinkedIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL_Twitter {
            get {
                return this.URL_TwitterField;
            }
            set {
                if ((object.ReferenceEquals(this.URL_TwitterField, value) != true)) {
                    this.URL_TwitterField = value;
                    this.RaisePropertyChanged("URL_Twitter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL_Viadeo {
            get {
                return this.URL_ViadeoField;
            }
            set {
                if ((object.ReferenceEquals(this.URL_ViadeoField, value) != true)) {
                    this.URL_ViadeoField = value;
                    this.RaisePropertyChanged("URL_Viadeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SolarSystem.Mars.Model.ManagersService.Ville Ville {
            get {
                return this.VilleField;
            }
            set {
                if ((object.ReferenceEquals(this.VilleField, value) != true)) {
                    this.VilleField = value;
                    this.RaisePropertyChanged("Ville");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ville_origine {
            get {
                return this.Ville_origineField;
            }
            set {
                if ((object.ReferenceEquals(this.Ville_origineField, value) != true)) {
                    this.Ville_origineField = value;
                    this.RaisePropertyChanged("Ville_origine");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibelleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_Role {
            get {
                return this.Code_RoleField;
            }
            set {
                if ((this.Code_RoleField.Equals(value) != true)) {
                    this.Code_RoleField = value;
                    this.RaisePropertyChanged("Code_Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Libelle {
            get {
                return this.LibelleField;
            }
            set {
                if ((object.ReferenceEquals(this.LibelleField, value) != true)) {
                    this.LibelleField = value;
                    this.RaisePropertyChanged("Libelle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="News", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class News : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_NewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_HeureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SolarSystem.Mars.Model.ManagersService.Membre MembreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mots_ClesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublieeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texte_CourtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Texte_LongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_News {
            get {
                return this.Code_NewsField;
            }
            set {
                if ((this.Code_NewsField.Equals(value) != true)) {
                    this.Code_NewsField = value;
                    this.RaisePropertyChanged("Code_News");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Heure {
            get {
                return this.Date_HeureField;
            }
            set {
                if ((this.Date_HeureField.Equals(value) != true)) {
                    this.Date_HeureField = value;
                    this.RaisePropertyChanged("Date_Heure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SolarSystem.Mars.Model.ManagersService.Membre Membre {
            get {
                return this.MembreField;
            }
            set {
                if ((object.ReferenceEquals(this.MembreField, value) != true)) {
                    this.MembreField = value;
                    this.RaisePropertyChanged("Membre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mots_Cles {
            get {
                return this.Mots_ClesField;
            }
            set {
                if ((object.ReferenceEquals(this.Mots_ClesField, value) != true)) {
                    this.Mots_ClesField = value;
                    this.RaisePropertyChanged("Mots_Cles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Publiee {
            get {
                return this.PublieeField;
            }
            set {
                if ((this.PublieeField.Equals(value) != true)) {
                    this.PublieeField = value;
                    this.RaisePropertyChanged("Publiee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texte_Court {
            get {
                return this.Texte_CourtField;
            }
            set {
                if ((object.ReferenceEquals(this.Texte_CourtField, value) != true)) {
                    this.Texte_CourtField = value;
                    this.RaisePropertyChanged("Texte_Court");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texte_Long {
            get {
                return this.Texte_LongField;
            }
            set {
                if ((object.ReferenceEquals(this.Texte_LongField, value) != true)) {
                    this.Texte_LongField = value;
                    this.RaisePropertyChanged("Texte_Long");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre {
            get {
                return this.TitreField;
            }
            set {
                if ((object.ReferenceEquals(this.TitreField, value) != true)) {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Projet", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Projet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvancementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_ProjetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SolarSystem.Mars.Model.ManagersService.Ville VilleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Avancement {
            get {
                return this.AvancementField;
            }
            set {
                if ((this.AvancementField.Equals(value) != true)) {
                    this.AvancementField = value;
                    this.RaisePropertyChanged("Avancement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_Projet {
            get {
                return this.Code_ProjetField;
            }
            set {
                if ((this.Code_ProjetField.Equals(value) != true)) {
                    this.Code_ProjetField = value;
                    this.RaisePropertyChanged("Code_Projet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SolarSystem.Mars.Model.ManagersService.Ville Ville {
            get {
                return this.VilleField;
            }
            set {
                if ((object.ReferenceEquals(this.VilleField, value) != true)) {
                    this.VilleField = value;
                    this.RaisePropertyChanged("Ville");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Publicite", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Publicite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_PubliciteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PresentationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublieeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_Publicite {
            get {
                return this.Code_PubliciteField;
            }
            set {
                if ((this.Code_PubliciteField.Equals(value) != true)) {
                    this.Code_PubliciteField = value;
                    this.RaisePropertyChanged("Code_Publicite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Presentation {
            get {
                return this.PresentationField;
            }
            set {
                if ((object.ReferenceEquals(this.PresentationField, value) != true)) {
                    this.PresentationField = value;
                    this.RaisePropertyChanged("Presentation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Publiee {
            get {
                return this.PublieeField;
            }
            set {
                if ((this.PublieeField.Equals(value) != true)) {
                    this.PublieeField = value;
                    this.RaisePropertyChanged("Publiee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Salon", Namespace="http://schemas.datacontract.org/2004/07/SolarSystem.Earth.Common")]
    [System.SerializableAttribute()]
    public partial class Salon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_SalonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_Heure_DebutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_Heure_FinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LieuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_Salon {
            get {
                return this.Code_SalonField;
            }
            set {
                if ((this.Code_SalonField.Equals(value) != true)) {
                    this.Code_SalonField = value;
                    this.RaisePropertyChanged("Code_Salon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Heure_Debut {
            get {
                return this.Date_Heure_DebutField;
            }
            set {
                if ((this.Date_Heure_DebutField.Equals(value) != true)) {
                    this.Date_Heure_DebutField = value;
                    this.RaisePropertyChanged("Date_Heure_Debut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Heure_Fin {
            get {
                return this.Date_Heure_FinField;
            }
            set {
                if ((this.Date_Heure_FinField.Equals(value) != true)) {
                    this.Date_Heure_FinField = value;
                    this.RaisePropertyChanged("Date_Heure_Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lieu {
            get {
                return this.LieuField;
            }
            set {
                if ((object.ReferenceEquals(this.LieuField, value) != true)) {
                    this.LieuField = value;
                    this.RaisePropertyChanged("Lieu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Publie {
            get {
                return this.PublieField;
            }
            set {
                if ((this.PublieField.Equals(value) != true)) {
                    this.PublieField = value;
                    this.RaisePropertyChanged("Publie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagersService.IClasseManager")]
    public interface IClasseManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasseManager/GetClasse", ReplyAction="http://tempuri.org/IClasseManager/GetClasseResponse")]
        SolarSystem.Mars.Model.ManagersService.Classe GetClasse(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasseManager/GetClasses", ReplyAction="http://tempuri.org/IClasseManager/GetClassesResponse")]
        SolarSystem.Mars.Model.ManagersService.Classe[] GetClasses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasseManager/GetClassesAvailables", ReplyAction="http://tempuri.org/IClasseManager/GetClassesAvailablesResponse")]
        SolarSystem.Mars.Model.ManagersService.Classe[] GetClassesAvailables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasseManager/AddClasse", ReplyAction="http://tempuri.org/IClasseManager/AddClasseResponse")]
        int AddClasse(SolarSystem.Mars.Model.ManagersService.Classe element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasseManager/EditClasse", ReplyAction="http://tempuri.org/IClasseManager/EditClasseResponse")]
        void EditClasse(SolarSystem.Mars.Model.ManagersService.Classe element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasseManager/DeleteClasse", ReplyAction="http://tempuri.org/IClasseManager/DeleteClasseResponse")]
        void DeleteClasse(int code, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClasseManagerChannel : SolarSystem.Mars.Model.ManagersService.IClasseManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClasseManagerClient : System.ServiceModel.ClientBase<SolarSystem.Mars.Model.ManagersService.IClasseManager>, SolarSystem.Mars.Model.ManagersService.IClasseManager {
        
        public ClasseManagerClient() {
        }
        
        public ClasseManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClasseManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClasseManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClasseManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolarSystem.Mars.Model.ManagersService.Classe GetClasse(int code) {
            return base.Channel.GetClasse(code);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Classe[] GetClasses() {
            return base.Channel.GetClasses();
        }
        
        public SolarSystem.Mars.Model.ManagersService.Classe[] GetClassesAvailables() {
            return base.Channel.GetClassesAvailables();
        }
        
        public int AddClasse(SolarSystem.Mars.Model.ManagersService.Classe element, string username, string password) {
            return base.Channel.AddClasse(element, username, password);
        }
        
        public void EditClasse(SolarSystem.Mars.Model.ManagersService.Classe element, string username, string password) {
            base.Channel.EditClasse(element, username, password);
        }
        
        public void DeleteClasse(int code, string username, string password) {
            base.Channel.DeleteClasse(code, username, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagersService.IConferenceManager")]
    public interface IConferenceManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceManager/GetConference", ReplyAction="http://tempuri.org/IConferenceManager/GetConferenceResponse")]
        SolarSystem.Mars.Model.ManagersService.Conference GetConference(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceManager/GetConferences", ReplyAction="http://tempuri.org/IConferenceManager/GetConferencesResponse")]
        SolarSystem.Mars.Model.ManagersService.Conference[] GetConferences(int indexFirstResult, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceManager/AddConference", ReplyAction="http://tempuri.org/IConferenceManager/AddConferenceResponse")]
        int AddConference(SolarSystem.Mars.Model.ManagersService.Conference element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceManager/EditConference", ReplyAction="http://tempuri.org/IConferenceManager/EditConferenceResponse")]
        void EditConference(SolarSystem.Mars.Model.ManagersService.Conference element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConferenceManager/DeleteConference", ReplyAction="http://tempuri.org/IConferenceManager/DeleteConferenceResponse")]
        void DeleteConference(int code, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConferenceManagerChannel : SolarSystem.Mars.Model.ManagersService.IConferenceManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConferenceManagerClient : System.ServiceModel.ClientBase<SolarSystem.Mars.Model.ManagersService.IConferenceManager>, SolarSystem.Mars.Model.ManagersService.IConferenceManager {
        
        public ConferenceManagerClient() {
        }
        
        public ConferenceManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConferenceManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConferenceManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConferenceManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolarSystem.Mars.Model.ManagersService.Conference GetConference(int code) {
            return base.Channel.GetConference(code);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Conference[] GetConferences(int indexFirstResult, int numberOfResults) {
            return base.Channel.GetConferences(indexFirstResult, numberOfResults);
        }
        
        public int AddConference(SolarSystem.Mars.Model.ManagersService.Conference element, string username, string password) {
            return base.Channel.AddConference(element, username, password);
        }
        
        public void EditConference(SolarSystem.Mars.Model.ManagersService.Conference element, string username, string password) {
            base.Channel.EditConference(element, username, password);
        }
        
        public void DeleteConference(int code, string username, string password) {
            base.Channel.DeleteConference(code, username, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagersService.ILienManager")]
    public interface ILienManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILienManager/GetLien", ReplyAction="http://tempuri.org/ILienManager/GetLienResponse")]
        SolarSystem.Mars.Model.ManagersService.Lien GetLien(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILienManager/GetLiens", ReplyAction="http://tempuri.org/ILienManager/GetLiensResponse")]
        SolarSystem.Mars.Model.ManagersService.Lien[] GetLiens();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILienManager/AddLien", ReplyAction="http://tempuri.org/ILienManager/AddLienResponse")]
        int AddLien(SolarSystem.Mars.Model.ManagersService.Lien element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILienManager/EditLien", ReplyAction="http://tempuri.org/ILienManager/EditLienResponse")]
        void EditLien(SolarSystem.Mars.Model.ManagersService.Lien element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILienManager/DeleteLien", ReplyAction="http://tempuri.org/ILienManager/DeleteLienResponse")]
        void DeleteLien(int code, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILienManagerChannel : SolarSystem.Mars.Model.ManagersService.ILienManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LienManagerClient : System.ServiceModel.ClientBase<SolarSystem.Mars.Model.ManagersService.ILienManager>, SolarSystem.Mars.Model.ManagersService.ILienManager {
        
        public LienManagerClient() {
        }
        
        public LienManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LienManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LienManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LienManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolarSystem.Mars.Model.ManagersService.Lien GetLien(int code) {
            return base.Channel.GetLien(code);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Lien[] GetLiens() {
            return base.Channel.GetLiens();
        }
        
        public int AddLien(SolarSystem.Mars.Model.ManagersService.Lien element, string username, string password) {
            return base.Channel.AddLien(element, username, password);
        }
        
        public void EditLien(SolarSystem.Mars.Model.ManagersService.Lien element, string username, string password) {
            base.Channel.EditLien(element, username, password);
        }
        
        public void DeleteLien(int code, string username, string password) {
            base.Channel.DeleteLien(code, username, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagersService.IMembreManager")]
    public interface IMembreManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreManager/GetMembre", ReplyAction="http://tempuri.org/IMembreManager/GetMembreResponse")]
        SolarSystem.Mars.Model.ManagersService.Membre GetMembre(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreManager/GetMembresActives", ReplyAction="http://tempuri.org/IMembreManager/GetMembresActivesResponse")]
        SolarSystem.Mars.Model.ManagersService.Membre[] GetMembresActives();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreManager/GetMembresBureau", ReplyAction="http://tempuri.org/IMembreManager/GetMembresBureauResponse")]
        SolarSystem.Mars.Model.ManagersService.Membre[] GetMembresBureau(SolarSystem.Mars.Model.ManagersService.Ville ville);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreManager/GetMembresNotInBureau", ReplyAction="http://tempuri.org/IMembreManager/GetMembresNotInBureauResponse")]
        SolarSystem.Mars.Model.ManagersService.Membre[] GetMembresNotInBureau(SolarSystem.Mars.Model.ManagersService.Ville ville);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreManager/GetMembresAlumnis", ReplyAction="http://tempuri.org/IMembreManager/GetMembresAlumnisResponse")]
        SolarSystem.Mars.Model.ManagersService.Membre[] GetMembresAlumnis(SolarSystem.Mars.Model.ManagersService.Ville ville);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreManager/GetMembresWaitingForValidation", ReplyAction="http://tempuri.org/IMembreManager/GetMembresWaitingForValidationResponse")]
        SolarSystem.Mars.Model.ManagersService.Membre[] GetMembresWaitingForValidation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreManager/Login", ReplyAction="http://tempuri.org/IMembreManager/LoginResponse")]
        SolarSystem.Mars.Model.ManagersService.Membre Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreManager/ChangePassword", ReplyAction="http://tempuri.org/IMembreManager/ChangePasswordResponse")]
        void ChangePassword(string username, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreManager/ExistsUsername", ReplyAction="http://tempuri.org/IMembreManager/ExistsUsernameResponse")]
        bool ExistsUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreManager/ExistsMembre", ReplyAction="http://tempuri.org/IMembreManager/ExistsMembreResponse")]
        bool ExistsMembre(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreManager/Register", ReplyAction="http://tempuri.org/IMembreManager/RegisterResponse")]
        int Register(SolarSystem.Mars.Model.ManagersService.Membre membre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreManager/RequestLostPassword", ReplyAction="http://tempuri.org/IMembreManager/RequestLostPasswordResponse")]
        void RequestLostPassword(string username, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreManager/SetNewPasswordAfterLost", ReplyAction="http://tempuri.org/IMembreManager/SetNewPasswordAfterLostResponse")]
        void SetNewPasswordAfterLost(string username, string newPassword, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreManager/AddMembre", ReplyAction="http://tempuri.org/IMembreManager/AddMembreResponse")]
        int AddMembre(SolarSystem.Mars.Model.ManagersService.Membre element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreManager/EditMembre", ReplyAction="http://tempuri.org/IMembreManager/EditMembreResponse")]
        void EditMembre(SolarSystem.Mars.Model.ManagersService.Membre element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembreManager/DeleteMembre", ReplyAction="http://tempuri.org/IMembreManager/DeleteMembreResponse")]
        void DeleteMembre(int code, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMembreManagerChannel : SolarSystem.Mars.Model.ManagersService.IMembreManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MembreManagerClient : System.ServiceModel.ClientBase<SolarSystem.Mars.Model.ManagersService.IMembreManager>, SolarSystem.Mars.Model.ManagersService.IMembreManager {
        
        public MembreManagerClient() {
        }
        
        public MembreManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MembreManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MembreManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MembreManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolarSystem.Mars.Model.ManagersService.Membre GetMembre(int code) {
            return base.Channel.GetMembre(code);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Membre[] GetMembresActives() {
            return base.Channel.GetMembresActives();
        }
        
        public SolarSystem.Mars.Model.ManagersService.Membre[] GetMembresBureau(SolarSystem.Mars.Model.ManagersService.Ville ville) {
            return base.Channel.GetMembresBureau(ville);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Membre[] GetMembresNotInBureau(SolarSystem.Mars.Model.ManagersService.Ville ville) {
            return base.Channel.GetMembresNotInBureau(ville);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Membre[] GetMembresAlumnis(SolarSystem.Mars.Model.ManagersService.Ville ville) {
            return base.Channel.GetMembresAlumnis(ville);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Membre[] GetMembresWaitingForValidation() {
            return base.Channel.GetMembresWaitingForValidation();
        }
        
        public SolarSystem.Mars.Model.ManagersService.Membre Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public void ChangePassword(string username, string oldPassword, string newPassword) {
            base.Channel.ChangePassword(username, oldPassword, newPassword);
        }
        
        public bool ExistsUsername(string username) {
            return base.Channel.ExistsUsername(username);
        }
        
        public bool ExistsMembre(string username, string password) {
            return base.Channel.ExistsMembre(username, password);
        }
        
        public int Register(SolarSystem.Mars.Model.ManagersService.Membre membre) {
            return base.Channel.Register(membre);
        }
        
        public void RequestLostPassword(string username, string email) {
            base.Channel.RequestLostPassword(username, email);
        }
        
        public void SetNewPasswordAfterLost(string username, string newPassword, string key) {
            base.Channel.SetNewPasswordAfterLost(username, newPassword, key);
        }
        
        public int AddMembre(SolarSystem.Mars.Model.ManagersService.Membre element, string username, string password) {
            return base.Channel.AddMembre(element, username, password);
        }
        
        public void EditMembre(SolarSystem.Mars.Model.ManagersService.Membre element, string username, string password) {
            base.Channel.EditMembre(element, username, password);
        }
        
        public void DeleteMembre(int code, string username, string password) {
            base.Channel.DeleteMembre(code, username, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagersService.INewsManager")]
    public interface INewsManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsManager/GetNews", ReplyAction="http://tempuri.org/INewsManager/GetNewsResponse")]
        SolarSystem.Mars.Model.ManagersService.News GetNews(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsManager/GetListNews", ReplyAction="http://tempuri.org/INewsManager/GetListNewsResponse")]
        SolarSystem.Mars.Model.ManagersService.News[] GetListNews();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsManager/GetListNewsLimited", ReplyAction="http://tempuri.org/INewsManager/GetListNewsLimitedResponse")]
        SolarSystem.Mars.Model.ManagersService.News[] GetListNewsLimited(int indexFirstElement, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsManager/AddNews", ReplyAction="http://tempuri.org/INewsManager/AddNewsResponse")]
        int AddNews(SolarSystem.Mars.Model.ManagersService.News element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsManager/EditNews", ReplyAction="http://tempuri.org/INewsManager/EditNewsResponse")]
        void EditNews(SolarSystem.Mars.Model.ManagersService.News element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsManager/DeleteNews", ReplyAction="http://tempuri.org/INewsManager/DeleteNewsResponse")]
        void DeleteNews(int code, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewsManagerChannel : SolarSystem.Mars.Model.ManagersService.INewsManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewsManagerClient : System.ServiceModel.ClientBase<SolarSystem.Mars.Model.ManagersService.INewsManager>, SolarSystem.Mars.Model.ManagersService.INewsManager {
        
        public NewsManagerClient() {
        }
        
        public NewsManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewsManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolarSystem.Mars.Model.ManagersService.News GetNews(int code) {
            return base.Channel.GetNews(code);
        }
        
        public SolarSystem.Mars.Model.ManagersService.News[] GetListNews() {
            return base.Channel.GetListNews();
        }
        
        public SolarSystem.Mars.Model.ManagersService.News[] GetListNewsLimited(int indexFirstElement, int numberOfResults) {
            return base.Channel.GetListNewsLimited(indexFirstElement, numberOfResults);
        }
        
        public int AddNews(SolarSystem.Mars.Model.ManagersService.News element, string username, string password) {
            return base.Channel.AddNews(element, username, password);
        }
        
        public void EditNews(SolarSystem.Mars.Model.ManagersService.News element, string username, string password) {
            base.Channel.EditNews(element, username, password);
        }
        
        public void DeleteNews(int code, string username, string password) {
            base.Channel.DeleteNews(code, username, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagersService.IProjetManager")]
    public interface IProjetManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjetManager/GetProjet", ReplyAction="http://tempuri.org/IProjetManager/GetProjetResponse")]
        SolarSystem.Mars.Model.ManagersService.Projet GetProjet(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjetManager/GetProjets", ReplyAction="http://tempuri.org/IProjetManager/GetProjetsResponse")]
        SolarSystem.Mars.Model.ManagersService.Projet[] GetProjets(int indexFirstElement, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjetManager/AddProjet", ReplyAction="http://tempuri.org/IProjetManager/AddProjetResponse")]
        int AddProjet(SolarSystem.Mars.Model.ManagersService.Projet element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjetManager/EditProjet", ReplyAction="http://tempuri.org/IProjetManager/EditProjetResponse")]
        void EditProjet(SolarSystem.Mars.Model.ManagersService.Projet element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjetManager/DeleteProjet", ReplyAction="http://tempuri.org/IProjetManager/DeleteProjetResponse")]
        void DeleteProjet(int code, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProjetManagerChannel : SolarSystem.Mars.Model.ManagersService.IProjetManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjetManagerClient : System.ServiceModel.ClientBase<SolarSystem.Mars.Model.ManagersService.IProjetManager>, SolarSystem.Mars.Model.ManagersService.IProjetManager {
        
        public ProjetManagerClient() {
        }
        
        public ProjetManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjetManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjetManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjetManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolarSystem.Mars.Model.ManagersService.Projet GetProjet(int code) {
            return base.Channel.GetProjet(code);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Projet[] GetProjets(int indexFirstElement, int numberOfResults) {
            return base.Channel.GetProjets(indexFirstElement, numberOfResults);
        }
        
        public int AddProjet(SolarSystem.Mars.Model.ManagersService.Projet element, string username, string password) {
            return base.Channel.AddProjet(element, username, password);
        }
        
        public void EditProjet(SolarSystem.Mars.Model.ManagersService.Projet element, string username, string password) {
            base.Channel.EditProjet(element, username, password);
        }
        
        public void DeleteProjet(int code, string username, string password) {
            base.Channel.DeleteProjet(code, username, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagersService.IPubliciteManager")]
    public interface IPubliciteManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPubliciteManager/GetPublicite", ReplyAction="http://tempuri.org/IPubliciteManager/GetPubliciteResponse")]
        SolarSystem.Mars.Model.ManagersService.Publicite GetPublicite(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPubliciteManager/GetPublicites", ReplyAction="http://tempuri.org/IPubliciteManager/GetPublicitesResponse")]
        SolarSystem.Mars.Model.ManagersService.Publicite[] GetPublicites();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPubliciteManager/AddPublicite", ReplyAction="http://tempuri.org/IPubliciteManager/AddPubliciteResponse")]
        int AddPublicite(SolarSystem.Mars.Model.ManagersService.Publicite element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPubliciteManager/EditPublicite", ReplyAction="http://tempuri.org/IPubliciteManager/EditPubliciteResponse")]
        void EditPublicite(SolarSystem.Mars.Model.ManagersService.Publicite element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPubliciteManager/DeletePublicite", ReplyAction="http://tempuri.org/IPubliciteManager/DeletePubliciteResponse")]
        void DeletePublicite(int code, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPubliciteManagerChannel : SolarSystem.Mars.Model.ManagersService.IPubliciteManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PubliciteManagerClient : System.ServiceModel.ClientBase<SolarSystem.Mars.Model.ManagersService.IPubliciteManager>, SolarSystem.Mars.Model.ManagersService.IPubliciteManager {
        
        public PubliciteManagerClient() {
        }
        
        public PubliciteManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PubliciteManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PubliciteManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PubliciteManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolarSystem.Mars.Model.ManagersService.Publicite GetPublicite(int code) {
            return base.Channel.GetPublicite(code);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Publicite[] GetPublicites() {
            return base.Channel.GetPublicites();
        }
        
        public int AddPublicite(SolarSystem.Mars.Model.ManagersService.Publicite element, string username, string password) {
            return base.Channel.AddPublicite(element, username, password);
        }
        
        public void EditPublicite(SolarSystem.Mars.Model.ManagersService.Publicite element, string username, string password) {
            base.Channel.EditPublicite(element, username, password);
        }
        
        public void DeletePublicite(int code, string username, string password) {
            base.Channel.DeletePublicite(code, username, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagersService.ISalonManager")]
    public interface ISalonManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalonManager/GetSalon", ReplyAction="http://tempuri.org/ISalonManager/GetSalonResponse")]
        SolarSystem.Mars.Model.ManagersService.Salon GetSalon(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalonManager/GetSalons", ReplyAction="http://tempuri.org/ISalonManager/GetSalonsResponse")]
        SolarSystem.Mars.Model.ManagersService.Salon[] GetSalons(int indexFirstElement, int numberOfResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalonManager/AddSalon", ReplyAction="http://tempuri.org/ISalonManager/AddSalonResponse")]
        int AddSalon(SolarSystem.Mars.Model.ManagersService.Salon element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalonManager/EditSalon", ReplyAction="http://tempuri.org/ISalonManager/EditSalonResponse")]
        void EditSalon(SolarSystem.Mars.Model.ManagersService.Salon element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalonManager/DeleteSalon", ReplyAction="http://tempuri.org/ISalonManager/DeleteSalonResponse")]
        void DeleteSalon(int code, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalonManagerChannel : SolarSystem.Mars.Model.ManagersService.ISalonManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalonManagerClient : System.ServiceModel.ClientBase<SolarSystem.Mars.Model.ManagersService.ISalonManager>, SolarSystem.Mars.Model.ManagersService.ISalonManager {
        
        public SalonManagerClient() {
        }
        
        public SalonManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalonManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalonManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalonManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolarSystem.Mars.Model.ManagersService.Salon GetSalon(int code) {
            return base.Channel.GetSalon(code);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Salon[] GetSalons(int indexFirstElement, int numberOfResults) {
            return base.Channel.GetSalons(indexFirstElement, numberOfResults);
        }
        
        public int AddSalon(SolarSystem.Mars.Model.ManagersService.Salon element, string username, string password) {
            return base.Channel.AddSalon(element, username, password);
        }
        
        public void EditSalon(SolarSystem.Mars.Model.ManagersService.Salon element, string username, string password) {
            base.Channel.EditSalon(element, username, password);
        }
        
        public void DeleteSalon(int code, string username, string password) {
            base.Channel.DeleteSalon(code, username, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagersService.IVilleManager")]
    public interface IVilleManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVilleManager/GetVille", ReplyAction="http://tempuri.org/IVilleManager/GetVilleResponse")]
        SolarSystem.Mars.Model.ManagersService.Ville GetVille(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVilleManager/GetVilles", ReplyAction="http://tempuri.org/IVilleManager/GetVillesResponse")]
        SolarSystem.Mars.Model.ManagersService.Ville[] GetVilles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVilleManager/AddVille", ReplyAction="http://tempuri.org/IVilleManager/AddVilleResponse")]
        int AddVille(SolarSystem.Mars.Model.ManagersService.Ville element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVilleManager/EditVille", ReplyAction="http://tempuri.org/IVilleManager/EditVilleResponse")]
        void EditVille(SolarSystem.Mars.Model.ManagersService.Ville element, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVilleManager/DeleteVille", ReplyAction="http://tempuri.org/IVilleManager/DeleteVilleResponse")]
        void DeleteVille(int code, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVilleManagerChannel : SolarSystem.Mars.Model.ManagersService.IVilleManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VilleManagerClient : System.ServiceModel.ClientBase<SolarSystem.Mars.Model.ManagersService.IVilleManager>, SolarSystem.Mars.Model.ManagersService.IVilleManager {
        
        public VilleManagerClient() {
        }
        
        public VilleManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VilleManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VilleManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VilleManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolarSystem.Mars.Model.ManagersService.Ville GetVille(int code) {
            return base.Channel.GetVille(code);
        }
        
        public SolarSystem.Mars.Model.ManagersService.Ville[] GetVilles() {
            return base.Channel.GetVilles();
        }
        
        public int AddVille(SolarSystem.Mars.Model.ManagersService.Ville element, string username, string password) {
            return base.Channel.AddVille(element, username, password);
        }
        
        public void EditVille(SolarSystem.Mars.Model.ManagersService.Ville element, string username, string password) {
            base.Channel.EditVille(element, username, password);
        }
        
        public void DeleteVille(int code, string username, string password) {
            base.Channel.DeleteVille(code, username, password);
        }
    }
}
